import { z } from 'zod';
import { defineEndpoint } from '../core/endpoint';
import { Empty } from '../core/envelope';
import { healthEndpoints } from '../core/ops';
import { Id, pageQuery } from '../core/primitives';
import { PublicSession, PublicSessionStatus } from '../domain/session';
import { PointsLedgerItem } from '../domain/points';
import * as S from './schemas';

const T = { auth: 'احراز هویت', me: 'حساب من', pub: 'محتوای عمومی', sec: 'نشست و امنیت' };

const otpLimits = [
  { limit: 5, windowSec: 3600, key: 'phone' },
  { limit: 20, windowSec: 3600, key: 'ip' }
] as const;

export const lowEndpoints = [
  defineEndpoint({
    id: 'L-01',
    service: 'low',
    method: 'post',
    path: '/auth/otp/request',
    summary: 'ارسال کد تأیید (OTP) به موبایل',
    description: 'ورود و ثبت‌نام یکپارچه. پاسخ برای شمارهٔ ثبت‌شده/ثبت‌نشده یکسان است (جلوگیری از user enumeration). ارسال پیامک غیرهمزمان صف می‌شود.',
    tags: [T.auth],
    auth: 'none',
    body: S.OtpRequestBody,
    response: S.OtpChallenge,
    errors: ['VALIDATION_FAILED', 'RATE_LIMITED', 'AUTH_OTP_SEND_FAILED'],
    rateLimit: [...otpLimits],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-02',
    service: 'low',
    method: 'post',
    path: '/auth/otp/verify',
    summary: 'تأیید OTP و صدور توکن',
    description: 'challenge تک‌مصرف است (idempotency با یکتایی DB). وب: refresh در cookie HttpOnly؛ سایرین: در بدنه.',
    tags: [T.auth],
    auth: 'none',
    body: S.OtpVerifyBody,
    response: S.AuthResult,
    errors: ['VALIDATION_FAILED', 'AUTH_OTP_INVALID', 'AUTH_OTP_EXPIRED', 'AUTH_OTP_EXHAUSTED', 'RATE_LIMITED', 'AUTH_ACCOUNT_DISABLED'],
    rateLimit: [{ limit: 30, windowSec: 600, key: 'ip' }],
    cache: 'no-store',
    idempotency: 'natural',
    setsCookie: true,
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-03',
    service: 'low',
    method: 'post',
    path: '/auth/login/password',
    summary: 'ورود با رمز عبور',
    description: 'خطای یکسان برای «شماره نیست» و «رمز غلط». مقایسهٔ رمز با زمان ثابت (argon2id).',
    tags: [T.auth],
    auth: 'none',
    body: S.PasswordLoginBody,
    response: S.AuthResult,
    errors: ['VALIDATION_FAILED', 'AUTH_INVALID_CREDENTIALS', 'RATE_LIMITED', 'AUTH_ACCOUNT_DISABLED'],
    rateLimit: [
      { limit: 5, windowSec: 900, key: 'ip+phone' },
      { limit: 50, windowSec: 900, key: 'ip' }
    ],
    cache: 'no-store',
    setsCookie: true,
    sloP95Ms: 350,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-04',
    service: 'low',
    method: 'post',
    path: '/auth/refresh',
    summary: 'تمدید نشست (rotation)',
    description: 'هر استفاده refresh قبلی را باطل می‌کند؛ استفادهٔ مجدد (reuse) کل family را revoke می‌کند. grace ۱۰ ثانیه برای مسابقهٔ چند-tab. وب: cookie `isra_rt` (CSRF: Origin allowlist + هدر X-Isra-Client).',
    tags: [T.auth],
    auth: 'refreshCookie',
    body: S.RefreshBody,
    response: S.RefreshResult,
    errors: ['AUTH_REFRESH_INVALID', 'RATE_LIMITED', 'AUTH_ACCOUNT_DISABLED'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'ip' }],
    cache: 'no-store',
    setsCookie: true,
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-05',
    service: 'low',
    method: 'post',
    path: '/auth/logout',
    summary: 'خروج (revoke نشست جاری)',
    description: 'idempotent؛ همیشه 200. cookie را پاک می‌کند.',
    tags: [T.auth],
    auth: 'bearerOrCookie',
    response: Empty,
    cache: 'no-store',
    idempotency: 'natural',
    setsCookie: true,
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-06',
    service: 'low',
    method: 'post',
    path: '/auth/step-up/otp/request',
    summary: 'درخواست OTP برای تأیید مجدد هویت (step-up)',
    tags: [T.sec],
    auth: 'bearer',
    response: S.OtpChallenge,
    errors: ['RATE_LIMITED', 'AUTH_OTP_SEND_FAILED'],
    rateLimit: [{ limit: 5, windowSec: 3600, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-07',
    service: 'low',
    method: 'post',
    path: '/auth/step-up/otp/verify',
    summary: 'تأیید OTP و صدور توکن step-up (۵ دقیقه)',
    tags: [T.sec],
    auth: 'bearer',
    body: S.StepUpVerifyBody,
    response: S.StepUpResult,
    errors: ['VALIDATION_FAILED', 'AUTH_OTP_INVALID', 'AUTH_OTP_EXPIRED', 'AUTH_OTP_EXHAUSTED'],
    rateLimit: [{ limit: 15, windowSec: 600, key: 'user' }],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'L-10',
    service: 'low',
    method: 'get',
    path: '/me',
    summary: 'حساب من',
    tags: [T.me],
    auth: 'bearer',
    response: S.Me,
    cache: 'no-store',
    sloP95Ms: 60,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-11',
    service: 'low',
    method: 'get',
    path: '/me/profile',
    summary: 'پروفایل من',
    tags: [T.me],
    auth: 'bearer',
    response: S.Profile,
    cache: 'no-store',
    sloP95Ms: 60,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-12',
    service: 'low',
    method: 'patch',
    path: '/me/profile',
    summary: 'به‌روزرسانی جزئی پروفایل',
    tags: [T.me],
    auth: 'bearer',
    body: S.ProfilePatchBody,
    response: S.Profile,
    errors: ['VALIDATION_FAILED'],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-13',
    service: 'low',
    method: 'put',
    path: '/me/password',
    summary: 'تعیین/تغییر رمز عبور',
    description: 'نیازمند step-up (مگر OTP کمتر از ۵ دقیقه). استثنا: وقتی `Me.mustChangePassword` است، به‌جای step-up `currentPassword` (رمز موقت) پذیرفته می‌شود. پس از موفقیت سایر نشست‌ها revoke می‌شوند و پرچم رمز موقت پاک می‌شود. رمز با argon2id ذخیره و هرگز لاگ نمی‌شود.',
    tags: [T.sec],
    auth: 'bearer',
    stepUp: true,
    body: S.SetPasswordBody,
    response: Empty,
    errors: ['VALIDATION_FAILED', 'AUTH_STEP_UP_REQUIRED', 'AUTH_INVALID_CREDENTIALS'],
    rateLimit: [{ limit: 5, windowSec: 900, key: 'user' }],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 350,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-14',
    service: 'low',
    method: 'get',
    path: '/me/sessions',
    summary: 'نشست‌ها و دستگاه‌های من',
    tags: [T.sec],
    auth: 'bearer',
    response: S.DeviceSession,
    list: true,
    query: pageQuery(50),
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-15',
    service: 'low',
    method: 'delete',
    path: '/me/sessions/{id}',
    summary: 'revoke یک نشست (نشست جاری = خروج)',
    tags: [T.sec],
    auth: 'bearer',
    params: z.object({ id: Id }),
    response: Empty,
    errors: ['NOT_FOUND'],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 100,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-16',
    service: 'low',
    method: 'post',
    path: '/me/sessions/revoke-others',
    summary: 'خروج از همهٔ نشست‌های دیگر',
    tags: [T.sec],
    auth: 'bearer',
    response: Empty,
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-17',
    service: 'low',
    method: 'get',
    path: '/me/inbox',
    summary: 'اینباکس (صفحه‌بندی‌شده)',
    tags: [T.me],
    auth: 'bearer',
    query: pageQuery(50).extend({ unreadOnly: z.coerce.boolean().default(false) }),
    response: S.InboxItem,
    list: true,
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-18',
    service: 'low',
    method: 'get',
    path: '/me/inbox/unread-count',
    summary: 'تعداد پیام‌های خوانده‌نشده (poll سبک)',
    tags: [T.me],
    auth: 'bearer',
    response: S.UnreadCount,
    cache: 'no-store',
    rateLimit: [{ limit: 120, windowSec: 60, key: 'user' }],
    sloP95Ms: 30,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-19',
    service: 'low',
    method: 'post',
    path: '/me/inbox/{id}/read',
    summary: 'علامت‌گذاری یک پیام به‌عنوان خوانده‌شده',
    tags: [T.me],
    auth: 'bearer',
    params: z.object({ id: Id }),
    response: Empty,
    errors: ['NOT_FOUND'],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 60,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-20',
    service: 'low',
    method: 'post',
    path: '/me/inbox/read-all',
    summary: 'خواندن همهٔ پیام‌ها',
    tags: [T.me],
    auth: 'bearer',
    response: Empty,
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-21',
    service: 'low',
    method: 'get',
    path: '/me/points',
    summary: 'خلاصهٔ امتیاز و نشان‌ها (aggregate از mid)',
    description: 'کلاینت low به api-mid مستقیم نمی‌زند (قفل #12)؛ low با internal REST خلاصه را می‌گیرد و کوتاه‌مدت (۱۵ ثانیه) در حافظه cache می‌کند.',
    tags: [T.me],
    auth: 'bearer',
    response: S.PointsSummary,
    errors: ['SERVICE_UNAVAILABLE'],
    cache: { scope: 'private', maxAgeSec: 15 },
    sloP95Ms: 150,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'L-30',
    service: 'low',
    method: 'get',
    path: '/public/sessions',
    summary: 'فهرست عمومی جلسات (guest و عضو)',
    description: 'بدون نیاز به توکن؛ جلسهٔ `draft` هرگز نمی‌آید. قابل cache در CDN و مرورگر با ETag.',
    tags: [T.pub],
    auth: 'none',
    query: pageQuery(50).extend({ status: PublicSessionStatus.optional() }),
    response: PublicSession,
    list: true,
    rateLimit: [{ limit: 120, windowSec: 60, key: 'ip' }],
    cache: { scope: 'public', maxAgeSec: 30, staleWhileRevalidateSec: 120, etag: true },
    sloP95Ms: 60,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-31',
    service: 'low',
    method: 'get',
    path: '/public/sessions/{id}',
    summary: 'جزئیات عمومی یک جلسه',
    tags: [T.pub],
    auth: 'none',
    params: z.object({ id: Id }),
    response: PublicSession,
    errors: ['NOT_FOUND'],
    rateLimit: [{ limit: 120, windowSec: 60, key: 'ip' }],
    cache: { scope: 'public', maxAgeSec: 30, staleWhileRevalidateSec: 120, etag: true },
    sloP95Ms: 50,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'L-90',
    service: 'low',
    method: 'get',
    path: '/.well-known/jwks.json',
    unversioned: true,
    raw: true,
    summary: 'JWKS: کلید(های) عمومی RS256 برای اعتبارسنجی محلی در mid/high',
    description: 'چرخش کلید: کلید جدید قبل از استفاده منتشر می‌شود و کلید قدیمی تا انقضای آخرین access (۱۵ دقیقه) می‌ماند.',
    tags: ['زیرساخت'],
    auth: 'none',
    response: S.Jwks,
    rateLimit: [{ limit: 60, windowSec: 60, key: 'ip' }],
    cache: { scope: 'public', maxAgeSec: 300, staleWhileRevalidateSec: 3600, etag: true },
    sloP95Ms: 20,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'L-22',
    service: 'low',
    method: 'delete',
    path: '/me',
    summary: 'حذف حساب من (حذف نرم + ناشناس‌سازی)',
    description: 'step-up لازم. دارندهٔ نقش سیستمی ⇒ CONFLICT(SYSTEM_PROTECTED). همهٔ نشست‌ها revoke و cookie پاک می‌شود؛ رویداد user.status.changed (source=self).',
    tags: [T.sec],
    auth: 'bearer',
    stepUp: true,
    body: S.DeleteMeBody,
    response: Empty,
    errors: ['VALIDATION_FAILED', 'AUTH_STEP_UP_REQUIRED', 'CONFLICT'],
    rateLimit: [{ limit: 3, windowSec: 86400, key: 'user' }],
    cache: 'no-store',
    idempotency: 'natural',
    setsCookie: true,
    sloP95Ms: 300,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'L-23',
    service: 'low',
    method: 'get',
    path: '/me/points/history',
    summary: 'تاریخچهٔ امتیاز من (دفتر؛ از mid)',
    tags: [T.me],
    auth: 'bearer',
    query: pageQuery(50),
    response: PointsLedgerItem,
    list: true,
    errors: ['SERVICE_UNAVAILABLE'],
    cache: { scope: 'private', maxAgeSec: 15 },
    sloP95Ms: 200,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'L-28',
    service: 'low',
    method: 'delete',
    path: '/me/inbox/{id}',
    summary: 'حذف یک پیام از اینباکس',
    tags: [T.me],
    auth: 'bearer',
    params: z.object({ id: Id }),
    response: Empty,
    errors: ['NOT_FOUND'],
    rateLimit: [{ limit: 120, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 60,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'L-32',
    service: 'low',
    method: 'get',
    path: '/public/config',
    summary: 'پیکربندی عمومی (حالت نگهداری، ثبت‌نام باز، نسخهٔ نشان‌ها)',
    tags: [T.pub],
    auth: 'none',
    response: S.PublicConfig,
    rateLimit: [{ limit: 120, windowSec: 60, key: 'ip' }],
    cache: { scope: 'public', maxAgeSec: 60, etag: true },
    sloP95Ms: 30,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'L-33',
    service: 'low',
    method: 'get',
    path: '/public/badges',
    summary: 'فهرست عمومی نشان‌ها (عنوان، آستانه، تصویر)',
    tags: [T.pub],
    auth: 'none',
    response: S.PublicBadge,
    list: true,
    query: pageQuery(100),
    rateLimit: [{ limit: 120, windowSec: 60, key: 'ip' }],
    cache: { scope: 'public', maxAgeSec: 300, etag: true },
    sloP95Ms: 30,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'L-34',
    service: 'low',
    method: 'get',
    path: '/public/badges/{id}/image',
    summary: 'تصویر نشان (باینری؛ v=hash ⇒ کش immutable)',
    description: 'تصویر از high (internal) گرفته و در low کش می‌شود. `v` با hash فعلی برابر ⇒ `Cache-Control: public, max-age=31536000, immutable`؛ وگرنه کوتاه‌مدت. فقط png/webp/jpeg (SVG هرگز). `X-Content-Type-Options: nosniff`.',
    tags: [T.pub],
    auth: 'none',
    raw: true,
    contentType: 'image/webp',
    params: z.object({ id: Id }),
    query: z.object({ v: z.string().regex(/^[a-f0-9]{16,64}$/).optional() }),
    response: z.string(),
    errors: ['NOT_FOUND'],
    rateLimit: [{ limit: 300, windowSec: 60, key: 'ip' }],
    cache: { scope: 'public', maxAgeSec: 31536000, etag: true },
    sloP95Ms: 30,
    since: '1.6.0'
  }),
  ...healthEndpoints('low', 'زیرساخت')
] as const;
