import { z } from 'zod';
import { defineEndpoint } from '../core/endpoint';
import { Empty } from '../core/envelope';
import { healthEndpoints } from '../core/ops';
import { Id, pageQuery } from '../core/primitives';
import { PointsSummary } from '../domain/points';
import { MidSession, SessionInput } from '../domain/session';
import * as S from './schemas';

const T = { me: 'کاربر', ses: 'جلسه', mem: 'عضویت', att: 'حضور', que: 'صف نوبت', ev: 'ارزیابی' };
const sid = z.object({ id: Id });
const writeLimit = (n = 60) => [{ limit: n, windowSec: 60, key: 'user' as const }];

export const midEndpoints = [
  defineEndpoint({ id: 'M-00', service: 'mid', method: 'get', path: '/me', summary: 'قابلیت‌های من در mid', tags: [T.me], auth: 'bearer', response: S.MidMe, cache: 'no-store', sloP95Ms: 50, since: '1.0.0' }),
  defineEndpoint({
    id: 'M-01',
    service: 'mid',
    method: 'get',
    path: '/me/sessions',
    summary: 'جلسه‌های من (عضو یا کادر)',
    description: '`scope=staff`: فقط جلساتی که نقش غیر-student دارم (شامل draft).',
    tags: [T.me],
    auth: 'bearer',
    query: S.MySessionsQuery,
    response: S.MySessionItem,
    list: true,
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-02',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/me',
    summary: 'عضویت، مجوزها و حضور من در یک جلسه',
    description: 'draft فقط برای اعضا/مدیر دیده می‌شود (وگرنه NOT_FOUND).',
    tags: [T.ses],
    auth: 'bearer',
    params: sid,
    response: S.SessionMe,
    errors: ['NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-03',
    service: 'mid',
    method: 'post',
    path: '/sessions',
    summary: 'ساخت جلسه (draft)',
    description: 'سازنده خودکار session_manager می‌شود.',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'session.create',
    body: SessionInput,
    response: MidSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-04',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}',
    summary: 'ویرایش جلسه (فقط draft/scheduled)',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'session.edit',
    params: sid,
    body: SessionInput,
    response: MidSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-05',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/transition',
    summary: 'چرخهٔ حیات: یک قدم رو به جلو',
    description: 'draft→scheduled→started→ended؛ پرش/برگشت ⇒ SESSION_INVALID_TRANSITION. رویداد realtime `session.state`.',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'session.transition',
    params: sid,
    body: S.TransitionBody,
    response: MidSession,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SESSION_INVALID_TRANSITION'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 150,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'M-10',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/members',
    summary: 'درخواست عضویت خودم',
    tags: [T.mem],
    auth: 'bearer',
    params: sid,
    response: S.Member,
    errors: ['NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(20),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-11',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/members',
    summary: 'فهرست اعضا/درخواست‌ها',
    tags: [T.mem],
    auth: 'bearer',
    permission: 'membership.approve',
    params: sid,
    query: S.MembersQuery,
    response: S.Member,
    list: true,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-12',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}/members/{memberId}',
    summary: 'تأیید یا رد عضویت',
    tags: [T.mem],
    auth: 'bearer',
    permission: 'membership.approve',
    params: z.object({ id: Id, memberId: Id }),
    body: S.DecideBody,
    response: S.Member,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(),
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-13',
    service: 'mid',
    method: 'put',
    path: '/sessions/{id}/members/{memberId}/roles',
    summary: 'تعیین نقش‌های عضو (پشتیبان/معلم/قرآن‌آموز)',
    tags: [T.mem],
    auth: 'bearer',
    permission: 'membership.roles',
    params: z.object({ id: Id, memberId: Id }),
    body: S.SetRolesBody,
    response: S.Member,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'M-20',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/attendance',
    summary: 'ثبت حضور (+۵ امتیاز فقط یک‌بار)',
    description: 'idempotent با یکتایی DB (sessionId,userId): دومین فراخوانی همان entry و pointsAwarded=0 برمی‌گرداند. فقط عضو تأییدشده و جلسهٔ started.',
    tags: [T.att],
    auth: 'bearer',
    params: sid,
    response: S.AttendanceResult,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-21',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/attendance',
    summary: 'حاضرین جلسه',
    tags: [T.att],
    auth: 'bearer',
    permission: 'attendance.view',
    params: sid,
    response: S.AttendanceList,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'M-30',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/queue',
    summary: 'پیوستن به صف نوبت (قرآن‌آموز حاضر)',
    tags: [T.que],
    auth: 'bearer',
    params: sid,
    response: S.QueueItem,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-31',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/queue/me',
    summary: 'انصراف از صف',
    tags: [T.que],
    auth: 'bearer',
    params: sid,
    response: Empty,
    errors: ['NOT_FOUND'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 100,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-32',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/queue',
    summary: 'وضعیت صف',
    description: 'برای `queue.manage` نام‌ها کامل؛ برای دیگران فقط نام نفر جاری، جایگاه خودم و تعداد منتظران.',
    tags: [T.que],
    auth: 'bearer',
    params: sid,
    response: S.QueueState,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: [{ limit: 120, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-33',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/queue/next',
    summary: 'نفر بعدی',
    description: 'نفر جاری ⇒ done، اولین منتظر ⇒ current؛ رویدادهای `queue.updated` و `queue.turned`.',
    tags: [T.que],
    auth: 'bearer',
    permission: 'queue.manage',
    params: sid,
    response: S.QueueState,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(60),
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-34',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}/queue/{itemId}',
    summary: 'بالا/پایین/انتقال به انتها/حذف از صف',
    tags: [T.que],
    auth: 'bearer',
    permission: 'queue.manage',
    params: z.object({ id: Id, itemId: Id }),
    body: S.QueueActBody,
    response: S.QueueState,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(120),
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'M-40',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/evaluations',
    summary: 'ثبت ارزیابی',
    description: '**فقط `eval.submit`** (teacher/supporter؛ manager به‌تنهایی نه — قفل #15). یک ارزیابی per نوبت. وزن‌ها از high.',
    tags: [T.ev],
    auth: 'bearer',
    permission: 'eval.submit',
    params: sid,
    body: S.EvaluationBody,
    response: S.Evaluation,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(60),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-41',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/evaluations',
    summary: 'ارزیابی‌ها (کادر: همه؛ دیگران: فقط خودم)',
    tags: [T.ev],
    auth: 'bearer',
    params: sid,
    query: pageQuery(100),
    response: S.Evaluation,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-42',
    service: 'mid',
    method: 'get',
    path: '/me/points',
    summary: 'خلاصهٔ امتیاز و نشان (برای UI mid)',
    tags: [T.me],
    auth: 'bearer',
    response: PointsSummary,
    cache: { scope: 'private', maxAgeSec: 15 },
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  ...healthEndpoints('mid', 'زیرساخت')
] as const;
