import { z } from 'zod';
import { defineEndpoint } from '../core/endpoint';
import { Empty } from '../core/envelope';
import { healthEndpoints } from '../core/ops';
import { Id, pageQuery } from '../core/primitives';
import { PointsSummary } from '../domain/points';
import { MidSession, PublicSession, SessionInput } from '../domain/session';
import { PointsLedgerItem } from '../domain/points';
import * as S from './schemas';

const T = { me: 'کاربر', ses: 'جلسه', mem: 'عضویت', att: 'حضور', que: 'صف نوبت', ev: 'ارزیابی', occ: 'نوبت برگزاری', inv: 'دعوت' };
const sm = z.object({ id: Id, memberId: Id });
const sid = z.object({ id: Id });
const writeLimit = (n = 60) => [{ limit: n, windowSec: 60, key: 'user' as const }];

export const midEndpoints = [
  defineEndpoint({ id: 'M-00', service: 'mid', method: 'get', path: '/me', summary: 'قابلیت‌های من در mid', tags: [T.me], auth: 'bearer', response: S.MidMe, cache: 'no-store', sloP95Ms: 50, since: '1.0.0' }),
  defineEndpoint({
    id: 'M-01',
    service: 'mid',
    method: 'get',
    path: '/me/sessions',
    summary: 'جلسه‌های من (عضو یا کادر)',
    description: '`scope=staff`: فقط جلساتی که نقش غیر-student دارم (شامل draft).',
    tags: [T.me],
    auth: 'bearer',
    query: S.MySessionsQuery,
    response: S.MySessionItem,
    list: true,
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-02',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/me',
    summary: 'عضویت، مجوزها و حضور من در یک جلسه',
    description: 'draft فقط برای اعضا/مدیر دیده می‌شود (وگرنه NOT_FOUND).',
    tags: [T.ses],
    auth: 'bearer',
    params: sid,
    response: S.SessionMe,
    errors: ['NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-03',
    service: 'mid',
    method: 'post',
    path: '/sessions',
    summary: 'ساخت جلسه (draft)',
    description: 'سازنده خودکار session_manager می‌شود.',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'session.create',
    body: SessionInput,
    response: MidSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-04',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}',
    summary: 'ویرایش جلسه (فقط draft/scheduled)',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'session.edit',
    params: sid,
    body: SessionInput,
    response: MidSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-05',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/transition',
    summary: 'چرخهٔ حیات: یک قدم رو به جلو',
    description: 'draft→scheduled→started→ended؛ پرش/برگشت ⇒ SESSION_INVALID_TRANSITION. رویداد realtime `session.state`. جلسهٔ once: started نوبت #۱ را باز و ended آن را می‌بندد؛ ended در هر نوع جلسه نوبت باز را می‌بندد (صف: current⇒done، waiting⇒حذف).',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'session.transition',
    params: sid,
    body: S.TransitionBody,
    response: MidSession,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SESSION_INVALID_TRANSITION'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 150,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'M-10',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/members',
    summary: 'درخواست عضویت خودم',
    description: 'joinPolicy=open ⇒ عضویت فوری (approved، quran_student)؛ invite_only ⇒ CONFLICT(JOIN_CLOSED)؛ پر بودن ⇒ CONFLICT(SESSION_FULL)؛ ردشده: پس از ۷ روز دوباره pending، پیش از آن CONFLICT(REQUEST_COOLDOWN, retryAfterSec). رویداد `members.updated`.',
    tags: [T.mem],
    auth: 'bearer',
    params: sid,
    response: S.Member,
    errors: ['NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(20),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-11',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/members',
    summary: 'فهرست اعضا/درخواست‌ها (فیلتر وضعیت/نقش/نام)',
    tags: [T.mem],
    auth: 'bearer',
    permission: 'membership.approve',
    params: sid,
    query: S.MembersQuery,
    response: S.Member,
    list: true,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-12',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}/members/{memberId}',
    summary: 'تأیید یا رد عضویت',
    description: 'ردشده را هم می‌توان بعداً تأیید کرد. ظرفیت پر ⇒ CONFLICT(SESSION_FULL). اعلان inbox `membership` + `members.updated`.',
    tags: [T.mem],
    auth: 'bearer',
    permission: 'membership.approve',
    params: z.object({ id: Id, memberId: Id }),
    body: S.DecideBody,
    response: S.Member,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(),
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-13',
    service: 'mid',
    method: 'put',
    path: '/sessions/{id}/members/{memberId}/roles',
    summary: 'تعیین نقش‌های عضو (پشتیبان/معلم/قرآن‌آموز)',
    description: 'روی عضو مدیر هم مجاز است: نقش مدیر حفظ و نقش‌های داده‌شده اضافه می‌شوند (مدیر+معلم مجاز؛ قفل #15). اعلان inbox به عضو + `members.updated`.',
    tags: [T.mem],
    auth: 'bearer',
    permission: 'membership.roles',
    params: z.object({ id: Id, memberId: Id }),
    body: S.SetRolesBody,
    response: S.Member,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'M-20',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/attendance',
    summary: 'ثبت حضور (+۵ امتیاز فقط یک‌بار)',
    description: 'روی **نوبت باز**؛ idempotent با یکتایی DB (occurrenceId,userId): دومین فراخوانی همان entry و pointsAwarded=0. فقط عضو تأییدشده؛ نبود نوبت باز ⇒ CONFLICT(OCCURRENCE_CLOSED).',
    tags: [T.att],
    auth: 'bearer',
    params: sid,
    response: S.AttendanceResult,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-21',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/attendance',
    summary: 'حاضرین یک نوبت (پیش‌فرض: نوبت باز یا آخرین)',
    tags: [T.att],
    auth: 'bearer',
    permission: 'attendance.view',
    params: sid,
    query: S.AttendanceQuery,
    response: S.AttendanceList,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'M-30',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/queue',
    summary: 'پیوستن به صف نوبت (قرآن‌آموز حاضر در نوبت باز)',
    tags: [T.que],
    auth: 'bearer',
    params: sid,
    response: S.QueueItem,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-31',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/queue/me',
    summary: 'انصراف از صف',
    tags: [T.que],
    auth: 'bearer',
    params: sid,
    response: Empty,
    errors: ['NOT_FOUND'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 100,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-32',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/queue',
    summary: 'وضعیت صف',
    description: 'برای `queue.manage` نام‌ها کامل؛ برای دیگران فقط نام نفر جاری، جایگاه خودم و تعداد منتظران. پیش‌فرض نوبت باز یا آخرین.',
    tags: [T.que],
    auth: 'bearer',
    params: sid,
    query: S.QueueQuery,
    response: S.QueueState,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: [{ limit: 120, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-33',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/queue/next',
    summary: 'نفر بعدی',
    description: 'نفر جاری ⇒ done، اولین منتظر ⇒ current؛ رویدادهای `queue.updated` و `queue.turned`.',
    tags: [T.que],
    auth: 'bearer',
    permission: 'queue.manage',
    params: sid,
    response: S.QueueState,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(60),
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-34',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}/queue/{itemId}',
    summary: 'بالا/پایین/انتقال به انتها/حذف از صف',
    description: 'فقط در نوبت باز (وگرنه CONFLICT(OCCURRENCE_CLOSED)).',
    tags: [T.que],
    auth: 'bearer',
    permission: 'queue.manage',
    params: z.object({ id: Id, itemId: Id }),
    body: S.QueueActBody,
    response: S.QueueState,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(120),
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'M-40',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/evaluations',
    summary: 'ثبت ارزیابی',
    description: '**فقط `eval.submit`** (teacher/supporter؛ manager به‌تنهایی نه — قفل #15). یک ارزیابی per آیتم صف؛ ارزیابی‌شونده باید هنوز عضو تأییدشده باشد. وزن‌ها از high.',
    tags: [T.ev],
    auth: 'bearer',
    permission: 'eval.submit',
    params: sid,
    body: S.EvaluationBody,
    response: S.Evaluation,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(60),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-41',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/evaluations',
    summary: 'ارزیابی‌ها (کادر: همه؛ دیگران: فقط خودم)',
    description: 'پیش‌فرض همهٔ نوبت‌ها؛ با `occurrenceId` فقط یک نوبت. باطل‌شده‌ها فقط با includeVoid=true (کادر).',
    tags: [T.ev],
    auth: 'bearer',
    params: sid,
    query: S.EvaluationsQuery,
    response: S.Evaluation,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-42',
    service: 'mid',
    method: 'get',
    path: '/me/points',
    summary: 'خلاصهٔ امتیاز و نشان (برای UI mid)',
    tags: [T.me],
    auth: 'bearer',
    response: PointsSummary,
    cache: { scope: 'private', maxAgeSec: 15 },
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-06',
    service: 'mid',
    method: 'get',
    path: '/sessions',
    summary: 'کشف و جست‌وجوی جلسات عمومی',
    description: 'فقط visibility=public و غیر draft؛ مرتب: شروع بعدی. برای android-mid/android-low (قفل #8 به‌روز شد).',
    tags: [T.ses],
    auth: 'bearer',
    query: S.SessionsSearchQuery,
    response: PublicSession,
    list: true,
    rateLimit: [{ limit: 120, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 15 },
    sloP95Ms: 120,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-07',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}',
    summary: 'حذف جلسهٔ draft توسط مدیر',
    description: 'فقط draft (وگرنه CONFLICT(SESSION_LOCKED))؛ حذف نرم.',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'session.edit',
    params: sid,
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-08',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/occurrences',
    summary: 'نوبت‌های برگزاری جلسه',
    tags: [T.occ],
    auth: 'bearer',
    permission: 'attendance.view',
    params: sid,
    query: S.OccurrencesQuery,
    response: S.Occurrence,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 100,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-09',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/occurrences',
    summary: 'باز کردن نوبت برگزاری (شروع کلاس امروز)',
    description: 'جلسه باید started باشد (وگرنه SESSION_LOCKED)؛ نوبت باز دیگر ⇒ CONFLICT(OCCURRENCE_LIVE). رویداد `occurrence.updated`.',
    tags: [T.occ],
    auth: 'bearer',
    permission: 'occurrence.manage',
    params: sid,
    response: S.Occurrence,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(20),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-19',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/occurrences/{occurrenceId}/close',
    summary: 'بستن نوبت برگزاری',
    description: 'صف: current⇒done، waiting⇒حذف. idempotent. رویداد `occurrence.updated`.',
    tags: [T.occ],
    auth: 'bearer',
    permission: 'occurrence.manage',
    params: z.object({ id: Id, occurrenceId: Id }),
    response: S.Occurrence,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(20),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-14',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/members/add',
    summary: 'افزودن مستقیم عضو (با شناسه یا شمارهٔ موبایل) با نقش',
    description: 'مدیر (`membership.roles`): هر نقش غیرمدیر؛ پشتیبان (`membership.approve`): فقط quran_student. عضو بلافاصله approved می‌شود. ظرفیت ⇒ outcome=full. جلسهٔ ended ⇒ CONFLICT(SESSION_LOCKED). شماره از طریق low resolve می‌شود (سقف durable per actor) و هرگز لاگ نمی‌شود. اعلان inbox + `members.updated`.',
    tags: [T.mem],
    auth: 'bearer',
    permission: 'membership.approve',
    params: sid,
    body: S.AddMembersBody,
    response: S.AddMembersResult,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT', 'RATE_LIMITED', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 20, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 400,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-15',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/members/{memberId}',
    summary: 'حذف عضو توسط کادر',
    description: 'مدیر: هر عضو غیرمدیر؛ پشتیبان: فقط قرآن‌آموز یا درخواست pending/rejected. مدیر ⇒ CONFLICT(SESSION_MANAGER_PROTECTED). صف فعال او حذف؛ حضور/ارزیابی/امتیاز می‌ماند. اعلان + `members.updated` + قطع socket.',
    tags: [T.mem],
    auth: 'bearer',
    permission: 'membership.approve',
    params: sm,
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-16',
    service: 'mid',
    method: 'put',
    path: '/sessions/{id}/members/{memberId}/manager',
    summary: 'اعطا/سلب/انتقال نقش مدیر جلسه',
    description: 'هدف باید approved باشد (NOT_APPROVED)؛ سلب آخرین مدیر ⇒ CONFLICT(LAST_HOLDER). stepDown=true ⇒ انتقال اتمیک (من مدیر نمی‌مانم).',
    tags: [T.mem],
    auth: 'bearer',
    permission: 'membership.roles',
    params: sm,
    body: S.ManagerBody,
    response: S.Member,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-17',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/membership',
    summary: 'ترک جلسه / لغو درخواست عضویت خودم',
    description: 'آخرین مدیر ⇒ CONFLICT(LAST_HOLDER). صف فعال حذف می‌شود.',
    tags: [T.mem],
    auth: 'bearer',
    params: sid,
    response: Empty,
    errors: ['NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(20),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-18',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/roster',
    summary: 'فهرست حضور و غیاب اعضا در یک نوبت',
    tags: [T.att],
    auth: 'bearer',
    permission: 'attendance.view',
    params: sid,
    query: S.RosterQuery,
    response: S.RosterItem,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-22',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/attendance/mark',
    summary: 'ثبت حضور اعضا توسط کادر (نوبت باز)',
    description: '+۵ فقط یک‌بار per (نوبت، کاربر)؛ هم‌زمانی با ثبت خودِ کاربر امن است. فقط اعضای تأییدشده. رویداد `attendance.updated`.',
    tags: [T.att],
    auth: 'bearer',
    permission: 'attendance.manage',
    params: sid,
    body: S.MarkAttendanceBody,
    response: S.MarkAttendanceResult,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(60),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-23',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/attendance/{userId}/revoke',
    summary: 'لغو حضور اشتباه (−۵ در دفتر امتیاز)',
    description: 'مدیر یا ثبت‌کنندهٔ همان حضور؛ امتیاز کل زیر ۰ نمی‌رود؛ نشان زیر آستانه پس گرفته می‌شود (تصمیم مالک ۱۴۰۵/۰۷/۱۵). idempotent.',
    tags: [T.att],
    auth: 'bearer',
    permission: 'attendance.manage',
    params: z.object({ id: Id, userId: Id }),
    body: S.RevokeAttendanceBody,
    response: S.RevokeAttendanceResult,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-35',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/queue/enqueue',
    summary: 'قرار دادن قرآن‌آموز در صف توسط کادر',
    description: 'نوبت باز لازم؛ هدف باید قرآن‌آموز تأییدشده باشد (NOT_STUDENT/NOT_APPROVED)؛ غایب ⇒ NOT_PRESENT مگر markPresent؛ تکراری ⇒ ALREADY_IN_QUEUE.',
    tags: [T.que],
    auth: 'bearer',
    permission: 'queue.manage',
    params: sid,
    body: S.EnqueueBody,
    response: S.QueueState,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(120),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-43',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}/evaluations/{evalId}',
    summary: 'ویرایش ارزیابی (ارزیاب اصلی، تا ۲۴ ساعت؛ پس از آن AUTH_FORBIDDEN)',
    description: 'امتیاز با وزن‌های ذخیره‌شده دوباره محاسبه؛ اختلاف در دفتر (evaluation_adjust). باطل‌شده ⇒ CONFLICT(EVALUATION_VOIDED). رویداد `eval.updated` + inbox.',
    tags: [T.ev],
    auth: 'bearer',
    permission: 'eval.submit',
    params: z.object({ id: Id, evalId: Id }),
    body: S.EvaluationPatchBody,
    response: S.Evaluation,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-44',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/evaluations/{evalId}/void',
    summary: 'باطل‌کردن ارزیابی (کسر امتیازش)',
    description: 'ارزیاب اصلی یا مدیر جلسه؛ دفتر: evaluation_void؛ نشان زیر آستانه پس گرفته می‌شود. idempotent.',
    tags: [T.ev],
    auth: 'bearer',
    permission: 'eval.submit',
    params: z.object({ id: Id, evalId: Id }),
    body: S.VoidEvaluationBody,
    response: S.Evaluation,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-46',
    service: 'mid',
    method: 'get',
    path: '/me/points/history',
    summary: 'تاریخچهٔ امتیاز من (دفتر)',
    tags: [T.me],
    auth: 'bearer',
    query: S.PointsLedgerQuery,
    response: PointsLedgerItem,
    list: true,
    cache: { scope: 'private', maxAgeSec: 15 },
    sloP95Ms: 100,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-50',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/invites',
    summary: 'ساخت لینک/کد دعوت',
    description: 'دعوت با نقش کادر نیازمند `membership.roles`. کد ۱۲۸ بیتی فقط یک‌بار برگردانده می‌شود (سرور hash نگه می‌دارد). حداکثر ۲۰ دعوت فعال per جلسه (LIMIT_REACHED).',
    tags: [T.inv],
    auth: 'bearer',
    permission: 'membership.approve',
    params: sid,
    body: S.CreateInviteBody,
    response: S.CreatedInvite,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-51',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/invites',
    summary: 'فهرست دعوت‌ها (بدون کد)',
    tags: [T.inv],
    auth: 'bearer',
    permission: 'membership.approve',
    params: sid,
    query: pageQuery(50),
    response: S.Invite,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 100,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-52',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/invites/{inviteId}',
    summary: 'باطل‌کردن دعوت',
    tags: [T.inv],
    auth: 'bearer',
    permission: 'membership.approve',
    params: z.object({ id: Id, inviteId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 100,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-53',
    service: 'mid',
    method: 'post',
    path: '/invites/accept',
    summary: 'پذیرش دعوت با کد',
    description: 'مصرف اتمیک؛ منقضی/تمام‌شده ⇒ INVITE_EXPIRED/INVITE_EXHAUSTED؛ پر ⇒ SESSION_FULL؛ ended ⇒ SESSION_LOCKED. عضو موجود ⇒ همان عضویت (pending/rejected ⇒ approved). سقف durable per کاربر و IP.',
    tags: [T.inv],
    auth: 'bearer',
    body: S.AcceptInviteBody,
    response: S.Member,
    errors: ['VALIDATION_FAILED', 'NOT_FOUND', 'CONFLICT', 'RATE_LIMITED'],
    rateLimit: [{ limit: 10, windowSec: 60, key: 'user' }, { limit: 30, windowSec: 60, key: 'ip' }],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  ...healthEndpoints('mid', 'زیرساخت')
] as const;
