import { z } from 'zod';
import { defineEndpoint } from '../core/endpoint';
import { Empty } from '../core/envelope';
import { healthEndpoints } from '../core/ops';
import { Id, pageQuery } from '../core/primitives';
import { PointsSummary } from '../domain/points';
import { MidSession, PublicSession, SessionInput } from '../domain/session';
import { PointsLedgerItem } from '../domain/points';
import * as S from './schemas';

const T = { me: 'کاربر', ses: 'جلسه', mem: 'عضویت', att: 'حضور', que: 'صف نوبت', ev: 'ارزیابی', occ: 'نوبت برگزاری', inv: 'دعوت', sup: 'پشتیبان', gal: 'گالری', cmt: 'کامنت', pub: 'عمومی (مهمان)' };
const sm = z.object({ id: Id, memberId: Id });
const sid = z.object({ id: Id });
const writeLimit = (n = 60) => [{ limit: n, windowSec: 60, key: 'user' as const }];

export const midEndpoints = [
  defineEndpoint({ id: 'M-00', service: 'mid', method: 'get', path: '/me', summary: 'قابلیت‌های من در mid', tags: [T.me], auth: 'bearer', response: S.MidMe, cache: 'no-store', sloP95Ms: 50, since: '1.0.0' }),
  defineEndpoint({
    id: 'M-01',
    service: 'mid',
    method: 'get',
    path: '/me/sessions',
    summary: 'جلسه‌های من (عضو یا کادر)',
    description: '`scope=staff`: فقط جلساتی که صاحب یا پشتیبانم (شامل draft). `role` فیلتر نقش من (owner/supporter/member).',
    tags: [T.me],
    auth: 'bearer',
    query: S.MySessionsQuery,
    response: S.MySessionItem,
    list: true,
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-02',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/me',
    summary: 'عضویت، مجوزها و حضور من در یک جلسه',
    description: 'draft فقط برای صاحب/پشتیبان دیده می‌شود (وگرنه NOT_FOUND). ۱.۷.۰: `role` و `permissions` بر اساس صاحب/پشتیبان؛ معیارهای ارزیابی از M-45.',
    tags: [T.ses],
    auth: 'bearer',
    params: sid,
    response: S.SessionMe,
    errors: ['NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-03',
    service: 'mid',
    method: 'post',
    path: '/sessions',
    summary: 'ساخت جلسه (draft)',
    description: 'نیازمند مجوز سیستمی `session.create` (نقش teacher یا grant). سازنده **صاحب** (owner) جلسه می‌شود و همهٔ مجوزهای جلسه را دارد؛ پشتیبان‌های ثابت او خودکار در جلسه مؤثرند.',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'session.create',
    body: SessionInput,
    response: MidSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-04',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}',
    summary: 'ویرایش جلسه (فقط draft/scheduled)',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'session.edit',
    params: sid,
    body: SessionInput,
    response: MidSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-05',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/transition',
    summary: 'چرخهٔ حیات: یک قدم رو به جلو',
    description: 'draft→scheduled→started→ended؛ پرش/برگشت ⇒ SESSION_INVALID_TRANSITION. رویداد realtime `session.state`. جلسهٔ once: started نوبت #۱ را باز و ended آن را می‌بندد؛ ended در هر نوع جلسه نوبت باز را می‌بندد (صف: current⇒done، waiting⇒حذف).',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'session.edit',
    params: sid,
    body: S.TransitionBody,
    response: MidSession,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SESSION_INVALID_TRANSITION'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 150,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'M-10',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/members',
    summary: 'درخواست عضویت خودم',
    description: 'joinPolicy=open ⇒ عضویت فوری (approved، quran_student)؛ invite_only ⇒ CONFLICT(JOIN_CLOSED)؛ پر بودن ⇒ CONFLICT(SESSION_FULL)؛ ردشده: پس از ۷ روز دوباره pending، پیش از آن CONFLICT(REQUEST_COOLDOWN, retryAfterSec). رویداد `members.updated`.',
    tags: [T.mem],
    auth: 'bearer',
    params: sid,
    response: S.Member,
    errors: ['NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(20),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-11',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/members',
    summary: 'فهرست اعضا/درخواست‌ها (فیلتر وضعیت/نام)',
    tags: [T.mem],
    auth: 'bearer',
    description: '۱.۷.۰: فقط اعضا (بدون صاحب/پشتیبان). دارندهٔ `membership.approve` (بدون manage) هم فهرست را می‌بیند تا درخواست‌ها را بررسی کند.',
    permission: 'membership.manage',
    params: sid,
    query: S.MembersQuery,
    response: S.Member,
    list: true,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-12',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}/members/{memberId}',
    summary: 'تأیید یا رد عضویت',
    description: 'دارندهٔ `membership.approve` (صاحب یا پشتیبان). ردشده را هم می‌توان بعداً تأیید کرد. ظرفیت پر ⇒ CONFLICT(SESSION_FULL). اعلان inbox `membership` + `members.updated`.',
    tags: [T.mem],
    auth: 'bearer',
    permission: 'membership.approve',
    params: z.object({ id: Id, memberId: Id }),
    body: S.DecideBody,
    response: S.Member,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(),
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'M-20',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/attendance',
    summary: 'ثبت حضور (+۵ امتیاز فقط یک‌بار)',
    description: 'روی **نوبت باز**؛ idempotent با یکتایی DB (occurrenceId,userId): دومین فراخوانی همان entry و pointsAwarded=0. فقط عضو تأییدشده؛ نبود نوبت باز ⇒ CONFLICT(OCCURRENCE_CLOSED).',
    tags: [T.att],
    auth: 'bearer',
    params: sid,
    response: S.AttendanceResult,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-21',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/attendance',
    summary: 'حاضرین یک نوبت (پیش‌فرض: نوبت باز یا آخرین)',
    tags: [T.att],
    auth: 'bearer',
    permission: 'owner|supporter',
    params: sid,
    query: S.AttendanceQuery,
    response: S.AttendanceList,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'M-30',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/queue',
    summary: 'پیوستن به صف نوبت (قرآن‌آموز حاضر در نوبت باز)',
    tags: [T.que],
    auth: 'bearer',
    params: sid,
    response: S.QueueItem,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-31',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/queue/me',
    summary: 'انصراف از صف',
    tags: [T.que],
    auth: 'bearer',
    params: sid,
    response: Empty,
    errors: ['NOT_FOUND'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 100,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-32',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/queue',
    summary: 'وضعیت صف',
    description: 'برای `queue.manage` نام‌ها کامل؛ برای دیگران فقط نام نفر جاری، جایگاه خودم و تعداد منتظران. پیش‌فرض نوبت باز یا آخرین.',
    tags: [T.que],
    auth: 'bearer',
    params: sid,
    query: S.QueueQuery,
    response: S.QueueState,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: [{ limit: 120, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-33',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/queue/next',
    summary: 'نفر بعدی',
    description: 'نفر جاری ⇒ done، اولین منتظر ⇒ current؛ رویدادهای `queue.updated` و `queue.turned`.',
    tags: [T.que],
    auth: 'bearer',
    permission: 'queue.manage',
    params: sid,
    response: S.QueueState,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(60),
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-34',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}/queue/{itemId}',
    summary: 'بالا/پایین/انتقال به انتها/حذف از صف',
    description: 'فقط در نوبت باز (وگرنه CONFLICT(OCCURRENCE_CLOSED)).',
    tags: [T.que],
    auth: 'bearer',
    permission: 'queue.manage',
    params: z.object({ id: Id, itemId: Id }),
    body: S.QueueActBody,
    response: S.QueueState,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(120),
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),

  defineEndpoint({
    id: 'M-40',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/evaluations',
    summary: 'ثبت ارزیابی',
    description: 'ارزیاب (قفل #15، ۱.۷.۰): **صاحب جلسه** یا **پشتیبانِ دارای `eval.submit`** (ادمین از H-96/H-95). `scores` = همهٔ معیارهای فعال فعلی (M-45)؛ snapshot معیارها ذخیره می‌شود. یک ارزیابی per آیتم صف؛ ارزیابی‌شونده باید عضو تأییدشده باشد؛ خودارزیابی ⇒ CONFLICT(SELF_EVALUATION).',
    tags: [T.ev],
    auth: 'bearer',
    permission: 'eval.submit',
    params: sid,
    body: S.EvaluationBody,
    response: S.Evaluation,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(60),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-41',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/evaluations',
    summary: 'ارزیابی‌ها (صاحب/پشتیبان: همه؛ دیگران: فقط خودم)',
    description: 'پیش‌فرض همهٔ نوبت‌ها؛ با `occurrenceId` فقط یک نوبت. باطل‌شده‌ها فقط با includeVoid=true (کادر).',
    tags: [T.ev],
    auth: 'bearer',
    params: sid,
    query: S.EvaluationsQuery,
    response: S.Evaluation,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-42',
    service: 'mid',
    method: 'get',
    path: '/me/points',
    summary: 'خلاصهٔ امتیاز و نشان (برای UI mid)',
    tags: [T.me],
    auth: 'bearer',
    response: PointsSummary,
    cache: { scope: 'private', maxAgeSec: 15 },
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'M-06',
    service: 'mid',
    method: 'get',
    path: '/sessions',
    summary: 'کشف و جست‌وجوی جلسات عمومی',
    description: 'فقط visibility=public و غیر draft؛ مرتب: شروع بعدی. برای android-mid/android-low (قفل #8 به‌روز شد).',
    tags: [T.ses],
    auth: 'bearer',
    query: S.SessionsSearchQuery,
    response: PublicSession,
    list: true,
    rateLimit: [{ limit: 120, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 15 },
    sloP95Ms: 120,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-07',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}',
    summary: 'حذف جلسهٔ draft توسط صاحب',
    description: 'فقط draft (وگرنه CONFLICT(SESSION_LOCKED))؛ حذف نرم.',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'session.edit',
    params: sid,
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-08',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/occurrences',
    summary: 'نوبت‌های برگزاری جلسه',
    tags: [T.occ],
    auth: 'bearer',
    permission: 'owner|supporter',
    params: sid,
    query: S.OccurrencesQuery,
    response: S.Occurrence,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 100,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-09',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/occurrences',
    summary: 'باز کردن نوبت برگزاری (شروع کلاس امروز)',
    description: 'جلسه باید started باشد (وگرنه SESSION_LOCKED)؛ نوبت باز دیگر ⇒ CONFLICT(OCCURRENCE_LIVE). رویداد `occurrence.updated`.',
    tags: [T.occ],
    auth: 'bearer',
    permission: 'occurrence.manage',
    params: sid,
    response: S.Occurrence,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(20),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-19',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/occurrences/{occurrenceId}/close',
    summary: 'بستن نوبت برگزاری',
    description: 'صف: current⇒done، waiting⇒حذف. idempotent. رویداد `occurrence.updated`.',
    tags: [T.occ],
    auth: 'bearer',
    permission: 'occurrence.manage',
    params: z.object({ id: Id, occurrenceId: Id }),
    response: S.Occurrence,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(20),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-14',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/members/add',
    summary: 'افزودن مستقیم عضو (با شناسه یا شمارهٔ موبایل)',
    description: '۱.۷.۰: فقط عضو (بدون نقش؛ پشتیبان از M-65). عضو بلافاصله approved می‌شود. ظرفیت ⇒ outcome=full. جلسهٔ ended ⇒ CONFLICT(SESSION_LOCKED). شماره از طریق low resolve می‌شود (سقف durable per actor) و هرگز لاگ نمی‌شود. اعلان inbox + `members.updated`.',
    tags: [T.mem],
    auth: 'bearer',
    permission: 'membership.manage',
    params: sid,
    body: S.AddMembersBody,
    response: S.AddMembersResult,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT', 'RATE_LIMITED', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 20, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 400,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-15',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/members/{memberId}',
    summary: 'حذف عضو توسط کادر',
    description: '۱.۷.۰: هر عضو یا درخواست (صاحب عضو نیست؛ پشتیبان از M-67 حذف می‌شود). صف فعال او حذف؛ حضور/ارزیابی/امتیاز می‌ماند. اعلان + `members.updated` + قطع socket.',
    tags: [T.mem],
    auth: 'bearer',
    permission: 'membership.manage',
    params: sm,
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-17',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/membership',
    summary: 'ترک جلسه / لغو درخواست عضویت خودم',
    description: 'صف فعال حذف می‌شود. صاحب جلسه عضو نیست (CONFLICT(SESSION_MANAGER_PROTECTED) — تغییر صاحب فقط با H-74).',
    tags: [T.mem],
    auth: 'bearer',
    params: sid,
    response: Empty,
    errors: ['NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(20),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-18',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/roster',
    summary: 'فهرست حضور و غیاب اعضا در یک نوبت',
    tags: [T.att],
    auth: 'bearer',
    permission: 'owner|supporter',
    params: sid,
    query: S.RosterQuery,
    response: S.RosterItem,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-22',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/attendance/mark',
    summary: 'ثبت حضور اعضا توسط کادر (نوبت باز)',
    description: '+۵ فقط یک‌بار per (نوبت، کاربر)؛ هم‌زمانی با ثبت خودِ کاربر امن است. فقط اعضای تأییدشده. رویداد `attendance.updated`.',
    tags: [T.att],
    auth: 'bearer',
    permission: 'attendance.manage',
    params: sid,
    body: S.MarkAttendanceBody,
    response: S.MarkAttendanceResult,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(60),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-23',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/attendance/{userId}/revoke',
    summary: 'لغو حضور اشتباه (−۵ در دفتر امتیاز)',
    description: 'صاحب یا ثبت‌کنندهٔ همان حضور؛ امتیاز کل زیر ۰ نمی‌رود؛ نشان زیر آستانه پس گرفته می‌شود (تصمیم مالک ۱۴۰۵/۰۷/۱۵). idempotent.',
    tags: [T.att],
    auth: 'bearer',
    permission: 'attendance.manage',
    params: z.object({ id: Id, userId: Id }),
    body: S.RevokeAttendanceBody,
    response: S.RevokeAttendanceResult,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-35',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/queue/enqueue',
    summary: 'قرار دادن قرآن‌آموز در صف توسط کادر',
    description: 'نوبت باز لازم؛ هدف باید عضو تأییدشده باشد (NOT_APPROVED)؛ غایب ⇒ NOT_PRESENT مگر markPresent (نیازمند attendance.manage)؛ تکراری ⇒ ALREADY_IN_QUEUE.',
    tags: [T.que],
    auth: 'bearer',
    permission: 'queue.manage',
    params: sid,
    body: S.EnqueueBody,
    response: S.QueueState,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(120),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-43',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}/evaluations/{evalId}',
    summary: 'ویرایش ارزیابی (ارزیاب اصلی یا صاحب، تا ۲۴ ساعت؛ پس از آن AUTH_FORBIDDEN)',
    description: 'فقط معیارهای همان snapshot؛ امتیاز با وزن/سقف ذخیره‌شده دوباره محاسبه؛ اختلاف در دفتر (evaluation_adjust). باطل‌شده ⇒ CONFLICT(EVALUATION_VOIDED). رویداد `eval.updated` + inbox.',
    tags: [T.ev],
    auth: 'bearer',
    permission: 'eval.submit',
    params: z.object({ id: Id, evalId: Id }),
    body: S.EvaluationPatchBody,
    response: S.Evaluation,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-44',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/evaluations/{evalId}/void',
    summary: 'باطل‌کردن ارزیابی (کسر امتیازش)',
    description: 'ارزیاب اصلی یا صاحب جلسه؛ دفتر: evaluation_void؛ نشان زیر آستانه پس گرفته می‌شود. idempotent.',
    tags: [T.ev],
    auth: 'bearer',
    permission: 'eval.submit',
    params: z.object({ id: Id, evalId: Id }),
    body: S.VoidEvaluationBody,
    response: S.Evaluation,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-46',
    service: 'mid',
    method: 'get',
    path: '/me/points/history',
    summary: 'تاریخچهٔ امتیاز من (دفتر)',
    tags: [T.me],
    auth: 'bearer',
    query: S.PointsLedgerQuery,
    response: PointsLedgerItem,
    list: true,
    cache: { scope: 'private', maxAgeSec: 15 },
    sloP95Ms: 100,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-50',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/invites',
    summary: 'ساخت لینک/کد دعوت',
    description: '۱.۷.۰: دعوت فقط برای عضویت (بدون نقش). کد ۱۲۸ بیتی فقط یک‌بار برگردانده می‌شود (سرور hash نگه می‌دارد). حداکثر ۲۰ دعوت فعال per جلسه (LIMIT_REACHED).',
    tags: [T.inv],
    auth: 'bearer',
    permission: 'membership.manage',
    params: sid,
    body: S.CreateInviteBody,
    response: S.CreatedInvite,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(10),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-51',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/invites',
    summary: 'فهرست دعوت‌ها (بدون کد)',
    tags: [T.inv],
    auth: 'bearer',
    permission: 'membership.manage',
    params: sid,
    query: pageQuery(50),
    response: S.Invite,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 100,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-52',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/invites/{inviteId}',
    summary: 'باطل‌کردن دعوت',
    tags: [T.inv],
    auth: 'bearer',
    permission: 'membership.manage',
    params: z.object({ id: Id, inviteId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 100,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'M-53',
    service: 'mid',
    method: 'post',
    path: '/invites/accept',
    summary: 'پذیرش دعوت با کد',
    description: 'مصرف اتمیک؛ منقضی/تمام‌شده ⇒ INVITE_EXPIRED/INVITE_EXHAUSTED؛ پر ⇒ SESSION_FULL؛ ended ⇒ SESSION_LOCKED. عضو موجود ⇒ همان عضویت (pending/rejected ⇒ approved). سقف durable per کاربر و IP.',
    tags: [T.inv],
    auth: 'bearer',
    body: S.AcceptInviteBody,
    response: S.Member,
    errors: ['VALIDATION_FAILED', 'NOT_FOUND', 'CONFLICT', 'RATE_LIMITED'],
    rateLimit: [{ limit: 10, windowSec: 60, key: 'user' }, { limit: 30, windowSec: 60, key: 'ip' }],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  // ───────── ۱.۷.۰ (docs-v2/31): معیار ارزیابی، پشتیبان، گالری، کامنت ─────────
  defineEndpoint({
    id: 'M-45',
    service: 'mid',
    method: 'get',
    path: '/evaluation-criteria',
    summary: 'معیارهای فعال فعلی ارزیابی (برای فرم و پیش‌نمایش امتیاز)',
    description: 'کش محلی mid از رویداد `evaluation.criteria.changed` (high). ارزیابی‌های ثبت‌شده snapshot خودشان را دارند.',
    tags: [T.ev],
    auth: 'bearer',
    response: S.ActiveCriteria,
    cache: { scope: 'private', maxAgeSec: 300, etag: true },
    sloP95Ms: 30,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-68',
    service: 'mid',
    method: 'get',
    path: '/session-permissions',
    summary: 'فهرست مجوزهای قابل‌واگذاری به پشتیبان (با عنوان فارسی)',
    tags: [T.sup],
    auth: 'bearer',
    response: S.SessionPermissionCatalog,
    cache: { scope: 'private', maxAgeSec: 3600, etag: true },
    sloP95Ms: 20,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-60',
    service: 'mid',
    method: 'get',
    path: '/me/supporters',
    summary: 'پشتیبان‌های ثابت من (استاد)',
    description: 'پشتیبان ثابت در همهٔ جلسه‌های حال و آیندهٔ من با همین مجوزها مؤثر است.',
    tags: [T.sup],
    auth: 'bearer',
    permission: 'supporter.manage_own',
    query: S.SupportersQuery,
    response: S.TeacherSupporter,
    list: true,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 100,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-61',
    service: 'mid',
    method: 'post',
    path: '/me/supporters',
    summary: 'افزودن پشتیبان ثابت (با شناسه یا شماره + مجوزها)',
    description: 'کاربر باید فعال باشد (CONFLICT(USER_NOT_ACTIVE))؛ ثبت‌نام‌نکرده ⇒ NOT_FOUND؛ خودم ⇒ CONFLICT(SELF_PROTECTED)؛ موجود ⇒ CONFLICT(ALREADY_SUPPORTER) (برای تغییر M-62). شماره از low resolve می‌شود با سقف durable per actor (مثل M-14) و هرگز لاگ نمی‌شود. حداکثر ۵۰ پشتیبان ثابت (LIMIT_REACHED). اعلان inbox به پشتیبان.',
    tags: [T.sup],
    auth: 'bearer',
    permission: 'supporter.manage_own',
    body: S.AddSupporterBody,
    response: S.TeacherSupporter,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT', 'RATE_LIMITED', 'SERVICE_UNAVAILABLE'],
    rateLimit: writeLimit(20),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 300,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-62',
    service: 'mid',
    method: 'patch',
    path: '/me/supporters/{userId}',
    summary: 'تغییر مجوزهای پشتیبان ثابت',
    description: 'جایگزینی کامل مجوزها؛ رویداد `supporters.updated` در جلسه‌های من.',
    tags: [T.sup],
    auth: 'bearer',
    permission: 'supporter.manage_own',
    params: z.object({ userId: Id }),
    body: S.SupporterPermissionsBody,
    response: S.TeacherSupporter,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-63',
    service: 'mid',
    method: 'delete',
    path: '/me/supporters/{userId}',
    summary: 'حذف پشتیبان ثابت',
    description: 'ردیف‌های per جلسهٔ همان کاربر دست نمی‌خورند. idempotent.',
    tags: [T.sup],
    auth: 'bearer',
    permission: 'supporter.manage_own',
    params: z.object({ userId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-64',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/supporters',
    summary: 'پشتیبان‌های مؤثر جلسه (منبع: ثابت استاد / per جلسه)',
    tags: [T.sup],
    auth: 'bearer',
    permission: 'owner|supporter',
    params: sid,
    query: S.SupportersQuery,
    response: S.SessionSupporter,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-65',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/supporters',
    summary: 'افزودن پشتیبان per جلسه',
    description: 'فقط صاحب جلسه. قواعد کاربر/شماره مثل M-61؛ صاحب ⇒ CONFLICT(SELF_PROTECTED)؛ ردیف per جلسهٔ موجود ⇒ CONFLICT(ALREADY_SUPPORTER). حداکثر ۲۰ پشتیبان per جلسه (LIMIT_REACHED). رویداد `supporters.updated` + inbox.',
    tags: [T.sup],
    auth: 'bearer',
    permission: 'owner',
    params: sid,
    body: S.AddSupporterBody,
    response: S.SessionSupporter,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT', 'RATE_LIMITED', 'SERVICE_UNAVAILABLE'],
    rateLimit: writeLimit(20),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 300,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-66',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}/supporters/{userId}',
    summary: 'تغییر مجوزهای پشتیبان per جلسه',
    description: 'فقط ردیف per جلسه (مجوزهای ثابت از M-62). نبود ردیف ⇒ NOT_FOUND.',
    tags: [T.sup],
    auth: 'bearer',
    permission: 'owner',
    params: z.object({ id: Id, userId: Id }),
    body: S.SupporterPermissionsBody,
    response: S.SessionSupporter,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-67',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/supporters/{userId}',
    summary: 'حذف پشتیبان per جلسه',
    description: 'پشتیبان ثابت استاد با این مسیر حذف نمی‌شود (M-63). idempotent؛ رویداد `supporters.updated`.',
    tags: [T.sup],
    auth: 'bearer',
    permission: 'owner',
    params: z.object({ id: Id, userId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-70',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/occurrences/{occurrenceId}/galleries',
    summary: 'گالری‌های یک نوبت (فیلترشده با سطح نمایش)',
    description: 'public: هر بیننده با gallery.view؛ members: اعضای تأییدشده + کادر؛ staff: صاحب/پشتیبان/ادمین. گالری‌هایی که نمی‌بینم اصلاً نمی‌آیند.',
    tags: [T.gal],
    auth: 'bearer',
    params: z.object({ id: Id, occurrenceId: Id }),
    query: S.GalleriesQuery,
    response: S.Gallery,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 100,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-71',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/occurrences/{occurrenceId}/galleries',
    summary: 'ساخت گالری برای یک نوبت',
    description: 'حداکثر ۲۰ گالری per نوبت (LIMIT_REACHED). رویداد `gallery.updated`.',
    tags: [T.gal],
    auth: 'bearer',
    permission: 'gallery.manage',
    params: z.object({ id: Id, occurrenceId: Id }),
    body: S.CreateGalleryBody,
    response: S.Gallery,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 150,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-72',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}/galleries/{galleryId}',
    summary: 'ویرایش عنوان/سطح نمایش/ترتیب گالری',
    tags: [T.gal],
    auth: 'bearer',
    permission: 'gallery.manage',
    params: z.object({ id: Id, galleryId: Id }),
    body: S.UpdateGalleryBody,
    response: S.Gallery,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-73',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/galleries/{galleryId}',
    summary: 'حذف گالری (نرم؛ فایل‌ها با job پاک می‌شوند)',
    tags: [T.gal],
    auth: 'bearer',
    permission: 'gallery.manage',
    params: z.object({ id: Id, galleryId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(30),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 150,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-74',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/galleries/{galleryId}/items',
    summary: 'آیتم‌های گالری',
    description: 'دسترسی طبق سطح نمایش گالری (وگرنه NOT_FOUND تا وجودش نشت نکند).',
    tags: [T.gal],
    auth: 'bearer',
    params: z.object({ id: Id, galleryId: Id }),
    query: S.GalleryItemsQuery,
    response: S.GalleryItem,
    list: true,
    errors: ['NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 100,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-75',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/galleries/{galleryId}/items',
    summary: 'بارگذاری فایل در گالری (بدنهٔ خام؛ `?title=`)',
    description:
      'بدنه = بایت‌های خام فایل با Content-Type واقعی (نه JSON/multipart). تصویر `image/jpeg|png|webp` ≤ ۵MB؛ صوت `audio/mpeg|mp4|ogg|webm|aac` ≤ ۵۰MB. نوع با magic bytes بررسی می‌شود؛ نوع ناهمخوان با گالری ⇒ CONFLICT(GALLERY_KIND_MISMATCH)؛ نوع ناشناخته ⇒ UNSUPPORTED_MEDIA_TYPE؛ حجم ⇒ PAYLOAD_TOO_LARGE؛ سهمیهٔ جلسه (`MEDIA_SESSION_QUOTA_MB`) ⇒ CONFLICT(QUOTA_EXCEEDED). JPEG: بخش‌های APP1/EXIF حذف می‌شوند. stream به فایل موقت و rename اتمیک در `MEDIA_DIR`؛ نبود MEDIA_DIR ⇒ SERVICE_UNAVAILABLE. رویداد `gallery.updated`.',
    tags: [T.gal],
    auth: 'bearer',
    permission: 'gallery.manage',
    params: z.object({ id: Id, galleryId: Id }),
    query: S.UploadItemQuery,
    rawBody: { contentTypes: [...S.GALLERY_IMAGE_TYPES, ...S.GALLERY_AUDIO_TYPES], maxBytes: S.GALLERY_AUDIO_MAX_BYTES },
    response: S.GalleryItem,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT', 'PAYLOAD_TOO_LARGE', 'UNSUPPORTED_MEDIA_TYPE', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 30, windowSec: 60, key: 'user' }, { limit: 500, windowSec: 86400, key: 'user' }],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 2000,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-76',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/galleries/{galleryId}/items/{itemId}',
    summary: 'حذف آیتم گالری (نرم؛ فایل با job پاک می‌شود)',
    tags: [T.gal],
    auth: 'bearer',
    permission: 'gallery.manage',
    params: z.object({ id: Id, galleryId: Id, itemId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(60),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 120,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-77',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/galleries/{galleryId}/items/{itemId}/content',
    summary: 'محتوای فایل آیتم گالری (Range برای صوت)',
    description:
      'پاسخ خام با Content-Type = mime آیتم؛ `Range` ⇒ 206؛ `ETag` = sha256 (If-None-Match ⇒ 304)؛ `Cache-Control: private, max-age=3600`؛ `X-Content-Type-Options: nosniff`؛ `Content-Disposition: inline`. دسترسی طبق سطح نمایش گالری (وگرنه NOT_FOUND). احراز: Bearer یا URL امضاشده از فیلد `url` آیتم (۱۰ دقیقه، مقید به کاربر)؛ امضای نامعتبر/منقضی ⇒ AUTH_REQUIRED؛ دسترسی کاربرِ امضا هم دوباره بررسی می‌شود.',
    tags: [T.gal],
    auth: 'bearerOrSignedUrl',
    raw: true,
    contentType: 'application/octet-stream',
    rangeRequests: true,
    params: z.object({ id: Id, galleryId: Id, itemId: Id }),
    query: z.object({
      exp: z.coerce.number().int().min(0).optional().meta({ description: 'انقضای امضا (epoch ثانیه)' }),
      u: Id.optional().meta({ description: 'کاربری که URL برایش امضا شده' }),
      sig: z.string().regex(/^[A-Za-z0-9_-]{43}$/).optional().meta({ description: 'HMAC-SHA256 base64url' })
    }),
    response: z.string(),
    errors: ['AUTH_REQUIRED', 'NOT_FOUND'],
    rateLimit: [{ limit: 600, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 3600, etag: true },
    sloP95Ms: 100,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-78',
    service: 'mid',
    method: 'get',
    path: '/public/sessions/{id}/galleries',
    summary: 'گالری‌های public یک جلسه برای مهمان (با `occurrenceId` اختیاری)',
    description:
      'بدون توکن؛ نیازمند `gallery.view` در baseline مهمان (رویداد `tier.baseline.changed`؛ نبود ⇒ AUTH_FORBIDDEN). فقط گالری‌های visibility=public؛ جلسهٔ draft ⇒ NOT_FOUND؛ جلسهٔ unlisted فقط با همین شناسهٔ مستقیم. آیتم‌ها درون‌خطی (≤ ۱۰۰ per گالری)؛ محتوا از M-79.',
    tags: [T.pub],
    auth: 'none',
    permission: 'gallery.view',
    params: sid,
    query: S.PublicGalleriesQuery,
    response: S.PublicGallery,
    list: true,
    errors: ['NOT_FOUND'],
    rateLimit: [{ limit: 120, windowSec: 60, key: 'ip' }],
    cache: { scope: 'public', maxAgeSec: 60, staleWhileRevalidateSec: 120, etag: true },
    sloP95Ms: 120,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-79',
    service: 'mid',
    method: 'get',
    path: '/public/galleries/{galleryId}/items/{itemId}/content',
    summary: 'محتوای آیتم گالری public (مهمان)',
    description:
      'فقط گالری visibility=public از جلسهٔ غیر draft (وگرنه NOT_FOUND). Content-Type = mime آیتم؛ `Range` ⇒ 206؛ `ETag` = sha256؛ `Cache-Control: public, max-age=86400`؛ `X-Content-Type-Options: nosniff`؛ `Content-Disposition: inline`.',
    tags: [T.pub],
    auth: 'none',
    permission: 'gallery.view',
    raw: true,
    contentType: 'application/octet-stream',
    rangeRequests: true,
    params: z.object({ galleryId: Id, itemId: Id }),
    response: z.string(),
    errors: ['NOT_FOUND'],
    rateLimit: [{ limit: 300, windowSec: 60, key: 'ip' }],
    cache: { scope: 'public', maxAgeSec: 86400, etag: true },
    sloP95Ms: 100,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-80',
    service: 'mid',
    method: 'get',
    path: '/sessions/{id}/occurrences/{occurrenceId}/comments',
    summary: 'کامنت‌های یک نوبت (`queueItemId?`، صفحه‌بندی؛ جدیدترین اول)',
    description:
      'فیلتر دیدن سمت سرور: commentVisibility=public ⇒ همهٔ بینندگان جلسه؛ reciter_only ⇒ کامنت تلاوت فقط برای نویسنده، خواننده و کادر و کامنت عمومی نوبت برای اعضا و کادر. پنهان‌شده (hidden) فقط برای کادر.',
    tags: [T.cmt],
    auth: 'bearer',
    params: z.object({ id: Id, occurrenceId: Id }),
    query: S.CommentsQuery,
    response: S.Comment,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: [{ limit: 120, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-81',
    service: 'mid',
    method: 'post',
    path: '/sessions/{id}/occurrences/{occurrenceId}/comments',
    summary: 'ثبت کامنت (حین تلاوت یا عمومی نوبت)',
    description:
      'عضو تأییدشده یا کادر با مجوز سیستمی `comment.post`. با `queueItemId` فقط وقتی آن آیتم current است (وگرنه CONFLICT(NOT_RECITING))؛ `atSec` را سرور از started_at حساب می‌کند. نوبت بسته ⇒ فقط کادر (وگرنه CONFLICT(OCCURRENCE_CLOSED)). commentsEnabled=false ⇒ CONFLICT(COMMENTS_DISABLED). سقف ۳۰/دقیقه per کاربر. رویداد `comment.created` فقط به سوکت‌های مجاز (reciter_only: اتاق شخصی `u:{id}`).',
    tags: [T.cmt],
    auth: 'bearer',
    permission: 'comment.post',
    params: z.object({ id: Id, occurrenceId: Id }),
    body: S.CreateCommentBody,
    response: S.Comment,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [{ limit: 30, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 150,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-82',
    service: 'mid',
    method: 'delete',
    path: '/sessions/{id}/comments/{commentId}',
    summary: 'حذف کامنت (نویسنده، یا کادر با comment.moderate)',
    description: 'حذف نرم؛ idempotent. رویداد `comment.updated`.',
    tags: [T.cmt],
    auth: 'bearer',
    params: z.object({ id: Id, commentId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(60),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 100,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'M-83',
    service: 'mid',
    method: 'patch',
    path: '/sessions/{id}/comments/{commentId}',
    summary: 'پنهان/آشکار کردن کامنت',
    description: 'رویداد `comment.updated`.',
    tags: [T.cmt],
    auth: 'bearer',
    permission: 'comment.moderate',
    params: z.object({ id: Id, commentId: Id }),
    body: S.ModerateCommentBody,
    response: S.Comment,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: writeLimit(60),
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 100,
    since: '1.7.0'
  }),
  ...healthEndpoints('mid', 'زیرساخت')
] as const;
