import { z } from 'zod';
import { defineEndpoint } from '../core/endpoint';
import { healthEndpoints } from '../core/ops';
import { Id, pageQuery } from '../core/primitives';
import * as S from './schemas';

const T = { me: 'هویت سیستمی', role: 'نقش‌ها و مجوزها', usr: 'کاربران', set: 'تنظیمات سراسری', aud: 'گزارش‌ها (audit)' };
const rl = { limit: 30, windowSec: 60, key: 'user' } as const;
const uid = z.object({ id: Id });

export const highEndpoints = [
  defineEndpoint({
    id: 'H-00',
    service: 'high',
    method: 'get',
    path: '/system/me',
    summary: 'هویت سیستمی من (نقش‌ها و مجوزها)',
    description: 'کاربر بدون نقش سیستم ⇒ AUTH_FORBIDDEN؛ UI «دسترسی ندارید» نشان می‌دهد.',
    tags: [T.me],
    auth: 'bearer',
    response: S.SystemMe,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 60,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-01',
    service: 'high',
    method: 'get',
    path: '/system/overview',
    summary: 'نمای کلی سیستم',
    tags: [T.me],
    auth: 'bearer',
    response: S.Overview,
    errors: ['AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 10 },
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-10',
    service: 'high',
    method: 'get',
    path: '/system/roles',
    summary: 'نقش‌های سیستم و ماتریس مجوز',
    tags: [T.role],
    auth: 'bearer',
    response: S.SystemRole,
    list: true,
    query: pageQuery(10),
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-11',
    service: 'high',
    method: 'get',
    path: '/system/permissions',
    summary: 'فهرست مجوزها',
    tags: [T.role],
    auth: 'bearer',
    response: S.PermissionInfo,
    list: true,
    query: pageQuery(50),
    errors: ['AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 300, etag: true },
    sloP95Ms: 40,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-12',
    service: 'high',
    method: 'put',
    path: '/system/roles/{key}/permissions',
    summary: 'ویرایش ماتریس مجوز یک نقش',
    description: 'نقش `developer` ثابت است ⇒ AUTH_FORBIDDEN؛ حذف مجوز قفل‌شده ⇒ CONFLICT(LOCKED_PERMISSION). رویداد outbox: `system.permission.changed`.',
    tags: [T.role],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.edit',
    params: z.object({ key: S.SystemRoleKey }),
    body: S.SetRolePermissionsBody,
    response: S.SystemRole,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-20',
    service: 'high',
    method: 'get',
    path: '/system/users',
    summary: 'جست‌وجوی کاربران',
    tags: [T.usr],
    auth: 'bearer',
    permission: 'system.users.view',
    query: pageQuery(50).extend(S.UsersQuery.shape),
    response: S.SystemUser,
    list: true,
    errors: ['AUTH_FORBIDDEN'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 150,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-21',
    service: 'high',
    method: 'get',
    path: '/system/users/{id}',
    summary: 'جزئیات یک کاربر',
    tags: [T.usr],
    auth: 'bearer',
    permission: 'system.users.view',
    params: uid,
    response: S.SystemUser,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-22',
    service: 'high',
    method: 'put',
    path: '/system/users/{id}/roles',
    summary: 'تخصیص/برداشتن نقش سیستم',
    description: 'قفل آخرین دارنده ⇒ CONFLICT(LAST_HOLDER)؛ تغییر نقش developer فقط توسط developer. رویداد outbox: `system.role.changed`.',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.assign',
    params: uid,
    body: S.SetUserRolesBody,
    response: S.SystemUser,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-23',
    service: 'high',
    method: 'put',
    path: '/system/users/{id}/grants',
    summary: 'تعیین مجوزهای مستقیم کاربر (ساخت جلسه)',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.assign',
    params: uid,
    body: S.SetUserGrantsBody,
    response: S.SystemUser,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-30',
    service: 'high',
    method: 'get',
    path: '/system/settings',
    summary: 'تنظیمات سراسری',
    tags: [T.set],
    auth: 'bearer',
    permission: 'system.settings.view',
    response: S.SystemSettings,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 50,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-31',
    service: 'high',
    method: 'put',
    path: '/system/settings',
    summary: 'به‌روزرسانی تنظیمات سراسری (optimistic concurrency)',
    description: '`version` قدیمی ⇒ CONFLICT(VERSION_MISMATCH). وزن جدید فقط روی ارزیابی‌های بعدی اثر دارد (D2). رویداد outbox: `system.settings.changed`.',
    tags: [T.set],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.settings.edit',
    body: S.UpdateSettingsBody,
    response: S.SystemSettings,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-40',
    service: 'high',
    method: 'get',
    path: '/system/audit',
    summary: 'گزارش اقدام‌ها (audit؛ فقط‌خواندنی)',
    tags: [T.aud],
    auth: 'bearer',
    permission: 'system.audit.view',
    query: pageQuery(50).extend(S.AuditQuery.shape),
    response: S.AuditEntry,
    list: true,
    errors: ['AUTH_FORBIDDEN'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  ...healthEndpoints('high', 'زیرساخت')
] as const;
