import { z } from 'zod';
import { defineEndpoint } from '../core/endpoint';
import { Empty } from '../core/envelope';
import { healthEndpoints } from '../core/ops';
import { Id, pageQuery } from '../core/primitives';
import { SessionInput } from '../domain/session';
import { Comment, Gallery, GalleryItem, GalleryItemsQuery, ModerateCommentBody, SessionPermissionCatalog, SessionSupporter, SupporterPermissionsBody, SupportersQuery, TeacherSupporter, TransitionBody, UpdateGalleryBody, UploadItemQuery, GALLERY_AUDIO_MAX_BYTES, GALLERY_AUDIO_TYPES, GALLERY_IMAGE_TYPES } from '../mid/schemas';
import * as S from './schemas';
import { Evaluation, MarkAttendanceResult, RevokeAttendanceResult } from '../mid/schemas';

const T = { evc: 'معیارهای ارزیابی', sup: 'پشتیبان‌ها', gal: 'گالری', cmt: 'کامنت', gam: 'امتیاز و نشان', msg: 'پیام همگانی', exp: 'خروجی داده', mod: 'اصلاح و نظارت جلسه', me: 'هویت سیستمی', rbac: 'نقش‌ها، ماژول‌ها و سطح دسترسی', acct: 'حساب من', role: 'نقش‌ها و مجوزها', usr: 'کاربران', ses: 'جلسه‌ها', rep: 'گزارش‌های تحلیلی', set: 'تنظیمات سراسری', aud: 'گزارش‌ها (audit)' };
const rl = { limit: 30, windowSec: 60, key: 'user' } as const;
const uid = z.object({ id: Id });

export const highEndpoints = [
  defineEndpoint({
    id: 'H-00',
    service: 'high',
    method: 'get',
    path: '/system/me',
    summary: 'هویت سیستمی من (نقش‌ها و مجوزها)',
    description: '۱.۷.۰: ورود به پنل نیازمند دست‌کم یک نقش tier=high **یا** یک مجوز `system.*` است (وگرنه AUTH_FORBIDDEN؛ UI «دسترسی ندارید»). `tiers` سطوح نقش‌های کاربر.',
    tags: [T.me],
    auth: 'bearer',
    response: S.SystemMe,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 60,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-01',
    service: 'high',
    method: 'get',
    path: '/system/overview',
    summary: 'نمای کلی سیستم',
    tags: [T.me],
    auth: 'bearer',
    response: S.Overview,
    errors: ['AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 10 },
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-10',
    service: 'high',
    method: 'get',
    path: '/system/roles',
    summary: 'فهرست نقش‌ها (ثابت و پویا، هر سه سطح) با مجوز، ماژول و قواعد step-up',
    description: '۱.۷.۰: فیلتر `tier`. نقش‌های ثابت: developer و super_admin (high)، teacher (mid)، guest و quran_student (low؛ ضمنی).',
    tags: [T.role],
    auth: 'bearer',
    response: S.SystemRole,
    list: true,
    query: S.RolesQuery,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-11',
    service: 'high',
    method: 'get',
    path: '/system/permissions',
    summary: 'فهرست مجوزها (رجیستری پویا؛ هر مجوز در یک ماژول)',
    description: 'سطح هر مجوز = سطح ماژولش (ModuleInfo.tier).',
    tags: [T.role],
    auth: 'bearer',
    response: S.PermissionInfo,
    list: true,
    query: pageQuery(50),
    errors: ['AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 300, etag: true },
    sloP95Ms: 40,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-12',
    service: 'high',
    method: 'put',
    path: '/system/roles/{key}/permissions',
    summary: 'ویرایش مجوزهای صریح یک نقش',
    description: 'نقش `developer` ثابت است ⇒ AUTH_FORBIDDEN؛ حذف مجوز قفل‌شده ⇒ CONFLICT(LOCKED_PERMISSION)؛ افزودن مجوزی که خودِ کاربر ندارد ⇒ AUTH_FORBIDDEN (ضد ارتقای دسترسی؛ developer معاف). مجوز ناموجود ⇒ NOT_FOUND. رویداد outbox: `system.permission.changed`. ۱.۷.۰: نقش tier=high ⇒ همین مجوز؛ نقش tier=mid ⇒ `system.roles.mid.manage`؛ tier=low (شامل guest/quran_student) ⇒ `system.roles.low.manage`. developer ثابت؛ ضد ارتقا (E2) بدون تغییر.',
    tags: [T.role],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.edit',
    permissionAny: ['system.roles.mid.manage', 'system.roles.low.manage'],
    params: z.object({ key: S.SystemRoleKey }),
    body: S.SetRolePermissionsBody,
    response: S.SystemRole,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-20',
    service: 'high',
    method: 'get',
    path: '/system/users',
    summary: 'جست‌وجوی کاربران',
    tags: [T.usr],
    auth: 'bearer',
    permission: 'system.users.view',
    query: pageQuery(50).extend(S.UsersQuery.shape),
    response: S.SystemUser,
    list: true,
    errors: ['AUTH_FORBIDDEN'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 150,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-21',
    service: 'high',
    method: 'get',
    path: '/system/users/{id}',
    summary: 'جزئیات یک کاربر',
    tags: [T.usr],
    auth: 'bearer',
    permission: 'system.users.view',
    params: uid,
    response: S.SystemUserDetail,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-22',
    service: 'high',
    method: 'put',
    path: '/system/users/{id}/roles',
    summary: 'تخصیص/برداشتن نقش سیستم',
    description: 'قفل آخرین دارنده ⇒ CONFLICT(LAST_HOLDER)؛ تغییر نقش developer فقط توسط developer. رویداد outbox: `system.role.changed`.',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.assign',
    params: uid,
    body: S.SetUserRolesBody,
    response: S.SystemUser,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-23',
    service: 'high',
    method: 'put',
    path: '/system/users/{id}/grants',
    summary: 'تعیین مجوزهای مستقیم کاربر (ساخت جلسه)',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.assign',
    params: uid,
    body: S.SetUserGrantsBody,
    response: S.SystemUser,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-30',
    service: 'high',
    method: 'get',
    path: '/system/settings',
    summary: 'تنظیمات سراسری',
    tags: [T.set],
    auth: 'bearer',
    permission: 'system.settings.view',
    response: S.SystemSettings,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 50,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-31',
    service: 'high',
    method: 'put',
    path: '/system/settings',
    summary: 'به‌روزرسانی تنظیمات سراسری (optimistic concurrency)',
    description: '`version` قدیمی ⇒ CONFLICT(VERSION_MISMATCH). ۱.۷.۰: فقط پرچم‌ها (وزن‌های ارزیابی ⇒ H-100..H-103). رویداد outbox: `system.settings.changed`.',
    tags: [T.set],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.settings.edit',
    body: S.UpdateSettingsBody,
    response: S.SystemSettings,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-40',
    service: 'high',
    method: 'get',
    path: '/system/audit',
    summary: 'گزارش اقدام‌ها (audit؛ فقط‌خواندنی)',
    tags: [T.aud],
    auth: 'bearer',
    permission: 'system.audit.view',
    query: pageQuery(50).extend(S.AuditQuery.shape),
    response: S.AuditEntry,
    list: true,
    errors: ['AUTH_FORBIDDEN'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  // ───────── حساب من (خودخدمتی؛ بدون permission سیستمی، فقط نقش سیستم) ─────────
  defineEndpoint({
    id: 'H-02',
    service: 'high',
    method: 'get',
    path: '/system/me/account',
    summary: 'حساب من (نام، شماره، وضعیت رمز)',
    tags: [T.acct],
    auth: 'bearer',
    response: S.MyAccount,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-03',
    service: 'high',
    method: 'patch',
    path: '/system/me/profile',
    summary: 'ویرایش نام و نام‌خانوادگی خودم',
    description: 'ویرایش در low انجام می‌شود (مالک حساب) و رویداد `user.profile.updated` به mid/high می‌رسد. تغییر شمارهٔ موبایل خودخدمتی نیست؛ مدیر با H-25 انجام می‌دهد.',
    tags: [T.acct],
    auth: 'bearer',
    body: S.UpdateMyProfileBody,
    response: S.MyAccount,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-04',
    service: 'high',
    method: 'put',
    path: '/system/me/password',
    summary: 'تعیین/تغییر رمز عبور خودم',
    description: 'نیازمند step-up؛ استثنا: وقتی `MyAccount.mustChangePassword` است `currentPassword` (رمز موقت) به‌جای step-up پذیرفته می‌شود. این تنها مسیر high است که با پرچم رمز موقت (claim `mcp`) مجاز است. پس از موفقیت سایر نشست‌ها revoke می‌شوند.',
    tags: [T.acct],
    auth: 'bearer',
    stepUp: true,
    body: S.SetMyPasswordBody,
    response: Empty,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'AUTH_INVALID_CREDENTIALS'],
    rateLimit: [{ limit: 5, windowSec: 900, key: 'user' }],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-05',
    service: 'high',
    method: 'get',
    path: '/system/me/sessions',
    summary: 'نشست‌ها و دستگاه‌های من',
    tags: [T.acct],
    auth: 'bearer',
    query: pageQuery(50),
    response: S.UserDeviceSession,
    list: true,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 150,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-06',
    service: 'high',
    method: 'delete',
    path: '/system/me/sessions/{id}',
    summary: 'revoke یک نشست خودم',
    tags: [T.acct],
    auth: 'bearer',
    params: uid,
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-07',
    service: 'high',
    method: 'post',
    path: '/system/me/sessions/revoke-others',
    summary: 'خروج از همهٔ نشست‌های دیگرِ خودم',
    tags: [T.acct],
    auth: 'bearer',
    response: Empty,
    errors: ['AUTH_FORBIDDEN'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.4.0'
  }),

  // ───────── مدیریت کاربر (دادهٔ حساب در low؛ high واسطهٔ مجاز + audit) ─────────
  defineEndpoint({
    id: 'H-24',
    service: 'high',
    method: 'post',
    path: '/system/users',
    summary: 'ساخت کاربر',
    description: 'حساب در low ساخته می‌شود و رویداد `user.registered` به high/mid می‌رسد. با `password` رمز موقت است و کاربر در اولین ورود باید عوضش کند. شمارهٔ تکراری ⇒ CONFLICT(PHONE_TAKEN).',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    body: S.CreateUserBody,
    response: S.SystemUserDetail,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-25',
    service: 'high',
    method: 'patch',
    path: '/system/users/{id}',
    summary: 'ویرایش نام/شمارهٔ کاربر',
    description: 'شمارهٔ تکراری ⇒ CONFLICT(PHONE_TAKEN). کاربر حذف‌شده قابل‌ویرایش نیست (CONFLICT USER_NOT_ACTIVE).',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    params: uid,
    body: S.UpdateUserBody,
    response: S.SystemUserDetail,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-26',
    service: 'high',
    method: 'post',
    path: '/system/users/{id}/status',
    summary: 'فعال/غیرفعال‌کردن کاربر',
    description: 'غیرفعال ⇒ همهٔ نشست‌ها revoke و ورود مسدود (AUTH_ACCOUNT_DISABLED). غیرفعال‌کردن خود یا آخرین developer ⇒ CONFLICT(SELF_PROTECTED/LAST_HOLDER).',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    params: uid,
    body: S.SetUserStatusBody,
    response: S.SystemUserDetail,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-27',
    service: 'high',
    method: 'delete',
    path: '/system/users/{id}',
    summary: 'حذف کاربر (حذف نرم + ناشناس‌سازی)',
    description: 'نام/شماره/رمز پاک و نشست‌ها revoke می‌شوند؛ تاریخچهٔ جلسه/حضور/امتیاز با نام «کاربر حذف‌شده» می‌ماند. برگشت‌پذیر نیست. حذف خود یا آخرین developer ⇒ CONFLICT.',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    params: uid,
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-28',
    service: 'high',
    method: 'put',
    path: '/system/users/{id}/password',
    summary: 'تعیین رمز موقت / حذف رمز کاربر',
    description: '`set`: رمز موقت (کاربر در اولین ورود باید عوض کند و نشست‌های او revoke می‌شود). `clear`: حذف رمز؛ ورود فقط با OTP. رمز هرگز لاگ/audit نمی‌شود.',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    params: uid,
    body: S.UserPasswordBody,
    response: Empty,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-29',
    service: 'high',
    method: 'post',
    path: '/system/users/{id}/logout-all',
    summary: 'خروج اجباری کاربر از همهٔ نشست‌ها',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    params: uid,
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-50',
    service: 'high',
    method: 'get',
    path: '/system/users/{id}/sessions',
    summary: 'نشست‌ها و دستگاه‌های یک کاربر (به تفکیک پنل/کلاینت)',
    tags: [T.usr],
    auth: 'bearer',
    permission: 'system.users.view',
    params: uid,
    query: pageQuery(50),
    response: S.UserDeviceSession,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 200,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-51',
    service: 'high',
    method: 'delete',
    path: '/system/users/{id}/sessions/{sessionId}',
    summary: 'revoke یک نشست کاربر',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    params: z.object({ id: Id, sessionId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),

  // ───────── مدیریت جلسه‌ها (دادهٔ جلسه در mid) ─────────
  defineEndpoint({
    id: 'H-60',
    service: 'high',
    method: 'get',
    path: '/system/sessions',
    summary: 'فهرست همهٔ جلسه‌ها با فیلتر',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    query: pageQuery(50).extend(S.AdminSessionsQuery.shape),
    response: S.AdminSession,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-61',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}',
    summary: 'جزئیات یک جلسه (شامل draft و حذف‌شده)',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    response: S.AdminSession,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 200,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-62',
    service: 'high',
    method: 'post',
    path: '/system/sessions',
    summary: 'ساخت جلسه از طرف یک کاربر',
    description: 'سازنده (پیش‌فرض خود ادمین) session_manager می‌شود؛ جلسه draft است.',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    body: S.AdminCreateSessionBody,
    response: S.AdminSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-63',
    service: 'high',
    method: 'patch',
    path: '/system/sessions/{id}',
    summary: 'ویرایش جلسه (فقط draft/scheduled؛ مثل M-04 ولی بدون نیاز به عضویت)',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: uid,
    body: SessionInput,
    response: S.AdminSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-64',
    service: 'high',
    method: 'post',
    path: '/system/sessions/{id}/transition',
    summary: 'چرخهٔ حیات جلسه: یک قدم رو به جلو',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: uid,
    body: TransitionBody,
    response: S.AdminSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SESSION_INVALID_TRANSITION', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-65',
    service: 'high',
    method: 'delete',
    path: '/system/sessions/{id}',
    summary: 'حذف جلسه (حذف نرم؛ از همهٔ فهرست‌های کاربران پنهان می‌شود)',
    description: 'تاریخچهٔ حضور/ارزیابی/امتیاز حفظ می‌شود و فقط در پنل مدیریت (`includeDeleted=true`) دیده می‌شود.',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: uid,
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-66',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/members',
    summary: 'اعضا و درخواست‌های عضویت جلسه',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    query: S.AdminMembersQuery,
    response: S.AdminMember,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-67',
    service: 'high',
    method: 'patch',
    path: '/system/sessions/{id}/members/{memberId}',
    summary: 'تأیید/رد عضویت',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: z.object({ id: Id, memberId: Id }),
    body: S.AdminDecideBody,
    response: S.AdminMember,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-69',
    service: 'high',
    method: 'delete',
    path: '/system/sessions/{id}/members/{memberId}',
    summary: 'حذف عضو از جلسه',
    description: '۱.۷.۰: فقط اعضا (صاحب عضو نیست؛ پشتیبان از H-109). صف فعال حذف؛ حضور/ارزیابی/امتیاز می‌ماند.',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: z.object({ id: Id, memberId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-70',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/attendance',
    summary: 'حاضرین یک نوبت (پیش‌فرض: نوبت باز یا آخرین)',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    query: S.AdminAttendanceQuery,
    response: S.AdminAttendanceList,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-71',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/queue',
    summary: 'صف نوبت جلسه (نمای کامل؛ پیش‌فرض نوبت باز یا آخرین)',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    query: z.object({ occurrenceId: Id.optional() }),
    response: S.AdminQueue,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-72',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/evaluations',
    summary: 'ارزیابی‌های جلسه (همهٔ نوبت‌ها یا یک نوبت)',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    query: S.AdminEvaluationsQuery,
    response: S.AdminEvaluations,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.4.0'
  }),

  // ───────── گزارش‌ها ─────────
  defineEndpoint({
    id: 'H-80',
    service: 'high',
    method: 'get',
    path: '/system/reports/overview',
    summary: 'گزارش جامع (کاربران، جلسه‌ها، مشارکت، پیامک، پنل‌ها) در بازه',
    description: 'بخش‌هایی که سرویس مبدأ در دسترس ندارد `null`/خالی می‌شوند (degraded)، نه خطا.',
    tags: [T.rep],
    auth: 'bearer',
    permission: 'system.reports.view',
    query: S.ReportRangeQuery,
    response: S.ReportOverview,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    rateLimit: [{ limit: 30, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 30 },
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-81',
    service: 'high',
    method: 'get',
    path: '/system/reports/registrations',
    summary: 'سری زمانی ثبت‌نام',
    tags: [T.rep],
    auth: 'bearer',
    permission: 'system.reports.view',
    query: S.ReportSeriesQuery,
    response: S.RegistrationsSeries,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    rateLimit: [{ limit: 30, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 30 },
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-82',
    service: 'high',
    method: 'get',
    path: '/system/reports/sessions',
    summary: 'سری زمانی جلسه‌ها (ساخته‌شده، برگزارشده، حضور)',
    tags: [T.rep],
    auth: 'bearer',
    permission: 'system.reports.view',
    query: S.ReportSeriesQuery,
    response: S.SessionsSeries,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 30, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 30 },
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-83',
    service: 'high',
    method: 'get',
    path: '/system/reports/otp',
    summary: 'سری زمانی پیامک OTP (درخواست/تأییدشده)',
    tags: [T.rep],
    auth: 'bearer',
    permission: 'system.reports.view',
    query: S.ReportSeriesQuery,
    response: S.OtpSeries,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 30, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 30 },
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-84',
    service: 'high',
    method: 'get',
    path: '/system/reports/leaderboard',
    summary: 'برترین کاربران بر اساس امتیاز',
    tags: [T.rep],
    auth: 'bearer',
    permission: 'system.reports.view',
    query: S.LeaderboardQuery,
    response: S.LeaderboardResponse,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 30, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 30 },
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-13',
    service: 'high',
    method: 'post',
    path: '/system/roles',
    summary: 'ساخت نقش پویا',
    description: 'کلید یکتا ⇒ CONFLICT(KEY_TAKEN)؛ مجوز/ماژول ناموجود ⇒ NOT_FOUND؛ مجوزی که سازنده ندارد ⇒ AUTH_FORBIDDEN (developer معاف). Idempotency-Key پشتیبانی می‌شود. ۱.۷.۰: نقش tier=high ⇒ همین مجوز؛ نقش tier=mid ⇒ `system.roles.mid.manage`؛ tier=low (شامل guest/quran_student) ⇒ `system.roles.low.manage`. developer ثابت؛ ضد ارتقا (E2) بدون تغییر.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.manage',
    permissionAny: ['system.roles.mid.manage', 'system.roles.low.manage'],
    body: S.CreateRoleBody,
    response: S.SystemRole,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 250,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-14',
    service: 'high',
    method: 'get',
    path: '/system/roles/{key}',
    summary: 'جزئیات یک نقش',
    tags: [T.rbac],
    auth: 'bearer',
    permission: 'system.users.view',
    params: z.object({ key: S.SystemRoleKey }),
    response: S.SystemRole,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-15',
    service: 'high',
    method: 'patch',
    path: '/system/roles/{key}',
    summary: 'ویرایش عنوان/توضیح نقش',
    description: '۱.۷.۰: نقش tier=high ⇒ همین مجوز؛ نقش tier=mid ⇒ `system.roles.mid.manage`؛ tier=low (شامل guest/quran_student) ⇒ `system.roles.low.manage`. developer ثابت؛ ضد ارتقا (E2) بدون تغییر.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.manage',
    permissionAny: ['system.roles.mid.manage', 'system.roles.low.manage'],
    params: z.object({ key: S.SystemRoleKey }),
    body: S.UpdateRoleBody,
    response: S.SystemRole,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-16',
    service: 'high',
    method: 'delete',
    path: '/system/roles/{key}',
    summary: 'حذف نقش پویا',
    description: 'نقش ثابت (developer، super_admin، teacher، guest، quran_student) ⇒ CONFLICT(SYSTEM_PROTECTED)؛ دارای دارنده ⇒ CONFLICT(ROLE_IN_USE) (ابتدا نقش را از کاربران بردارید). پاسخ = آخرین وضعیت نقش پیش از حذف. ۱.۷.۰: نقش tier=high ⇒ همین مجوز؛ نقش tier=mid ⇒ `system.roles.mid.manage`؛ tier=low (شامل guest/quran_student) ⇒ `system.roles.low.manage`. developer ثابت؛ ضد ارتقا (E2) بدون تغییر.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.manage',
    permissionAny: ['system.roles.mid.manage', 'system.roles.low.manage'],
    params: z.object({ key: S.SystemRoleKey }),
    response: S.SystemRole,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-17',
    service: 'high',
    method: 'put',
    path: '/system/roles/{key}/modules',
    summary: 'تعیین ماژول‌های کامل نقش',
    description: 'نقش به همهٔ مجوزهای حال و آیندهٔ هر ماژول دسترسی می‌یابد. developer ثابت است. ضد ارتقا: مجوز ماژول که کاربر ندارد ⇒ AUTH_FORBIDDEN. claim دارندگان نقش تازه می‌شود. ۱.۷.۰: نقش tier=high ⇒ همین مجوز؛ نقش tier=mid ⇒ `system.roles.mid.manage`؛ tier=low (شامل guest/quran_student) ⇒ `system.roles.low.manage`. developer ثابت؛ ضد ارتقا (E2) بدون تغییر.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.manage',
    permissionAny: ['system.roles.mid.manage', 'system.roles.low.manage'],
    params: z.object({ key: S.SystemRoleKey }),
    body: S.SetRoleModulesBody,
    response: S.SystemRole,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-18',
    service: 'high',
    method: 'put',
    path: '/system/roles/{key}/step-up',
    summary: 'قواعد step-up هر نقش per مجوز',
    description: 'override نقش روی پیش‌فرض مجوز. موثر برای کاربر: اگر هر منبع (نقش/grant) «required» بگوید ⇒ لازم؛ developer همیشه معاف. ۱.۷.۰: نقش tier=high ⇒ همین مجوز؛ نقش tier=mid ⇒ `system.roles.mid.manage`؛ tier=low (شامل guest/quran_student) ⇒ `system.roles.low.manage`. developer ثابت؛ ضد ارتقا (E2) بدون تغییر.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.stepup.manage',
    permissionAny: ['system.roles.mid.manage', 'system.roles.low.manage'],
    params: z.object({ key: S.SystemRoleKey }),
    body: S.SetRoleStepUpBody,
    response: S.SystemRole,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-85',
    service: 'high',
    method: 'post',
    path: '/system/permissions',
    summary: 'ساخت مجوز پویا',
    description: 'کلید یکتا ⇒ CONFLICT(KEY_TAKEN)؛ ماژول ناموجود ⇒ NOT_FOUND. مجوز پویا فقط داده است و در JWT/claim برای سرویس‌های مصرف‌کننده می‌آید؛ endpointهای سیستمی فقط مجوزهای سیستمی را اعمال می‌کنند.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.manage',
    body: S.CreatePermissionBody,
    response: S.PermissionInfo,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-86',
    service: 'high',
    method: 'patch',
    path: '/system/permissions/{key}',
    summary: 'ویرایش مجوز',
    description: 'مجوز سیستمی: فقط عنوان/توضیح/step-up پیش‌فرض/grantable؛ جابه‌جایی ماژول فقط برای مجوز پویا.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.manage',
    params: z.object({ key: S.PermissionKey }),
    body: S.UpdatePermissionBody,
    response: S.PermissionInfo,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-87',
    service: 'high',
    method: 'delete',
    path: '/system/permissions/{key}',
    summary: 'حذف مجوز پویا',
    description: 'مجوز سیستمی ⇒ CONFLICT(SYSTEM_PROTECTED). حذف از همهٔ نقش‌ها، grantها و قواعد step-up؛ claim دارندگان تازه می‌شود.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.manage',
    params: z.object({ key: S.PermissionKey }),
    response: S.PermissionInfo,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-88',
    service: 'high',
    method: 'get',
    path: '/system/modules',
    summary: 'فهرست ماژول‌ها',
    description: '۱.۷.۰: فیلتر `tier`.',
    tags: [T.rbac],
    auth: 'bearer',
    query: S.ModulesQuery,
    response: S.ModuleInfo,
    list: true,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 60, etag: true },
    sloP95Ms: 60,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-89',
    service: 'high',
    method: 'post',
    path: '/system/modules',
    summary: 'ساخت ماژول',
    description: 'کلید یکتا ⇒ CONFLICT(KEY_TAKEN).',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.manage',
    body: S.CreateModuleBody,
    response: S.ModuleInfo,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-90',
    service: 'high',
    method: 'patch',
    path: '/system/modules/{key}',
    summary: 'ویرایش ماژول',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.manage',
    params: z.object({ key: S.ModuleKey }),
    body: S.UpdateModuleBody,
    response: S.ModuleInfo,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-91',
    service: 'high',
    method: 'delete',
    path: '/system/modules/{key}',
    summary: 'حذف ماژول',
    description: 'ماژول سیستمی ⇒ CONFLICT(SYSTEM_PROTECTED)؛ دارای مجوز ⇒ CONFLICT(MODULE_NOT_EMPTY).',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.manage',
    params: z.object({ key: S.ModuleKey }),
    response: S.ModuleInfo,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-92',
    service: 'high',
    method: 'get',
    path: '/system/rbac/matrix',
    summary: 'ماتریس کامل نقش × مجوز × ماژول (یک درخواست برای UI)',
    description: 'همهٔ ماژول‌ها، مجوزها و نقش‌ها همراه قواعد step-up و `version` ماتریس. با If-None-Match ⇒ 304.',
    tags: [T.rbac],
    auth: 'bearer',
    permission: 'system.users.view',
    response: S.RbacMatrix,
    errors: ['AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 5, etag: true },
    sloP95Ms: 120,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-93',
    service: 'high',
    method: 'get',
    path: '/system/rbac/effective/{id}',
    summary: 'دسترسی مؤثر یک کاربر (با منبع هر مجوز و وضعیت step-up)',
    tags: [T.rbac],
    auth: 'bearer',
    permission: 'system.users.view',
    params: uid,
    response: S.EffectiveAccess,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 100,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-94',
    service: 'high',
    method: 'get',
    path: '/system/me/access',
    summary: 'دسترسی مؤثر من (مجوز، منبع و نیاز به step-up)',
    tags: [T.rbac],
    auth: 'bearer',
    response: S.EffectiveAccess,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 60,
    since: '1.5.0'
  }),
  // ───────── ۱.۶.۰ (docs-v2/30): عملیات کامل جلسه، امتیاز/نشان، پیام همگانی، خروجی ─────────
  defineEndpoint({
    id: 'H-73',
    service: 'high',
    method: 'post',
    path: '/system/sessions/{id}/members',
    summary: 'افزودن مستقیم اعضا (با شناسه یا شماره) — تا ۲۰۰ نفر',
    description: '۱.۷.۰: فقط عضو (بدون نقش؛ پشتیبان از H-108). عضو بلافاصله approved؛ pending/rejected ⇒ approved. شماره در high به کاربر نگاشت می‌شود؛ ثبت‌نام‌نکرده ⇒ not_found یا با createMissing ساخت کاربر (نیازمند system.users.manage هم). کاربر غیرفعال/حذف‌شده ⇒ not_active. ظرفیت ⇒ full. نتیجهٔ per آیتم (موفقیت جزئی مجاز). audit `session.members_add` بدون شماره.',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: uid,
    body: S.AdminAddMembersBody,
    response: S.AdminAddMembersResult,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 10, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 1500,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-74',
    service: 'high',
    method: 'put',
    path: '/system/sessions/{id}/owner',
    summary: 'تغییر استاد صاحب جلسه',
    description: '۱.۷.۰: صاحب جدید همهٔ مجوزهای جلسه را می‌گیرد (اگر عضو یا پشتیبان per جلسه بود، آن ردیف برداشته می‌شود)؛ صاحب قبلی طبق `previousOwner`. کاربر غیرفعال ⇒ CONFLICT(USER_NOT_ACTIVE)؛ همان صاحب فعلی ⇒ بدون تغییر. پشتیبان‌های ثابتِ صاحب قبلی دیگر در این جلسه مؤثر نیستند و پشتیبان‌های ثابت صاحب جدید مؤثر می‌شوند. audit `session.owner_transfer`.',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: uid,
    body: S.TransferOwnerBody,
    response: S.AdminSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-53',
    service: 'high',
    method: 'post',
    path: '/system/sessions/{id}/members/decide',
    summary: 'تأیید/رد گروهی درخواست‌های عضویت',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: uid,
    body: S.AdminDecideBulkBody,
    response: S.AdminDecideBulkResult,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 800,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-75',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/occurrences',
    summary: 'نوبت‌های برگزاری جلسه',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    query: pageQuery(50),
    response: S.AdminOccurrence,
    list: true,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-76',
    service: 'high',
    method: 'post',
    path: '/system/sessions/{id}/attendance',
    summary: 'ثبت حضور توسط ادمین (اصلاح؛ نوبت باز یا بسته)',
    description: '+۵ یک‌بار per نوبت. audit `session.attendance_add` با reason.',
    tags: [T.mod],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.moderate',
    params: uid,
    body: S.AdminMarkAttendanceBody,
    response: MarkAttendanceResult,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 400,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-77',
    service: 'high',
    method: 'post',
    path: '/system/sessions/{id}/attendance/{userId}/revoke',
    summary: 'لغو حضور اشتباه (−۵ در دفتر)',
    description: 'امتیاز کل زیر ۰ نمی‌رود؛ نشان زیر آستانه پس گرفته می‌شود. audit `session.attendance_revoke`.',
    tags: [T.mod],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: z.object({ id: Id, userId: Id }),
    body: S.AdminRevokeAttendanceBody,
    response: RevokeAttendanceResult,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-78',
    service: 'high',
    method: 'post',
    path: '/system/sessions/{id}/queue/next',
    summary: 'صف: نفر بعدی (ادمین)',
    description: 'نوبت باز لازم (OCCURRENCE_CLOSED)؛ شرط expectCurrentItemId ناهمخوان ⇒ QUEUE_STATE_CHANGED. step-up پیش‌فرض این مجوز none است.',
    tags: [T.mod],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.moderate',
    params: uid,
    body: S.AdminQueueNextBody,
    response: S.AdminQueue,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 120, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-79',
    service: 'high',
    method: 'patch',
    path: '/system/sessions/{id}/queue/{itemId}',
    summary: 'صف: بالا/پایین/انتها/حذف (ادمین)',
    tags: [T.mod],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.moderate',
    params: z.object({ id: Id, itemId: Id }),
    body: S.AdminQueueActBody,
    response: S.AdminQueue,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 120, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 250,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-95',
    service: 'high',
    method: 'post',
    path: '/system/sessions/{id}/evaluations/{evalId}/void',
    summary: 'باطل‌کردن ارزیابی (کسر امتیاز)',
    description: 'دفتر: evaluation_void؛ نشان زیر آستانه پس گرفته می‌شود. idempotent. audit `session.evaluation_void`.',
    tags: [T.mod],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: z.object({ id: Id, evalId: Id }),
    body: S.AdminVoidEvaluationBody,
    response: Evaluation,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-96',
    service: 'high',
    method: 'patch',
    path: '/system/sessions/{id}/evaluations/{evalId}',
    summary: 'اصلاح نمره‌های ارزیابی',
    description: '۱.۷.۰: `scores` فقط برای معیارهای snapshot همان ارزیابی؛ امتیاز با وزن/سقف ذخیره‌شده دوباره محاسبه؛ اختلاف در دفتر (evaluation_adjust). باطل‌شده ⇒ EVALUATION_VOIDED. audit `session.evaluation_patch`.',
    tags: [T.mod],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: z.object({ id: Id, evalId: Id }),
    body: S.AdminEvaluationPatchBody,
    response: Evaluation,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-52',
    service: 'high',
    method: 'get',
    path: '/system/users/{id}/memberships',
    summary: 'جلسه‌ها و نقش‌های یک کاربر (صاحب/پشتیبان/عضو)',
    tags: [T.usr],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    query: S.UserMembershipsQuery,
    response: S.UserMembership,
    list: true,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 300,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-97',
    service: 'high',
    method: 'get',
    path: '/system/users/{id}/points',
    summary: 'امتیاز، نشان‌ها و دفتر امتیاز یک کاربر',
    tags: [T.gam],
    auth: 'bearer',
    permission: 'system.users.view',
    params: uid,
    query: S.AdminUserPointsQuery,
    response: S.AdminUserPoints,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 300,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-98',
    service: 'high',
    method: 'post',
    path: '/system/users/{id}/points/adjust',
    summary: 'اصلاح دستی امتیاز (مثبت/منفی)',
    description: 'دفتر: admin_adjust؛ کل زیر ۰ نمی‌رود؛ نشان‌ها بر اساس امتیاز جدید اعطا/پس گرفته می‌شوند. audit `points.adjust`.',
    tags: [T.gam],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.points.manage',
    params: uid,
    body: S.PointsAdjustBody,
    response: S.PointsAdjustResult,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 300,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-32',
    service: 'high',
    method: 'get',
    path: '/system/badges',
    summary: 'فهرست نشان‌ها (همه، شامل غیرفعال)',
    tags: [T.gam],
    auth: 'bearer',
    query: pageQuery(100),
    response: S.AdminBadge,
    list: true,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 10, etag: true },
    sloP95Ms: 100,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-33',
    service: 'high',
    method: 'post',
    path: '/system/badges',
    summary: 'ساخت نشان',
    description: 'کلید تکراری ⇒ KEY_TAKEN؛ حداکثر ۵۰ نشان (LIMIT_REACHED). پس از تغییر، اعطا/پس‌گیری نشان برای همه بازمحاسبه می‌شود (پس‌زمینه). audit `badge.create`.',
    tags: [T.gam],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.badges.manage',
    body: S.CreateBadgeBody,
    response: S.AdminBadge,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 250,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-34',
    service: 'high',
    method: 'patch',
    path: '/system/badges/{id}',
    summary: 'ویرایش نشان (عنوان، آستانه، فعال/غیرفعال، ترتیب)',
    description: 'تغییر آستانه/فعال‌بودن ⇒ بازمحاسبهٔ دارندگان (اعطا یا پس‌گیری). audit `badge.update`.',
    tags: [T.gam],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.badges.manage',
    params: uid,
    body: S.UpdateBadgeBody,
    response: S.AdminBadge,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-35',
    service: 'high',
    method: 'delete',
    path: '/system/badges/{id}',
    summary: 'حذف نشان (از همهٔ دارندگان پس گرفته می‌شود)',
    tags: [T.gam],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.badges.manage',
    params: uid,
    response: S.AdminBadge,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-36',
    service: 'high',
    method: 'put',
    path: '/system/badges/{id}/image',
    summary: 'بارگذاری تصویر نشان (png/webp/jpeg ≤ ۲۰۰KB)',
    description: 'نوع واقعی با magic bytes بررسی؛ SVG ممنوع؛ ابعاد ≤ ۱۰۲۴px. hash تازه ⇒ آدرس جدید در L-34.',
    tags: [T.gam],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.badges.manage',
    params: uid,
    body: S.BadgeImageBody,
    response: S.AdminBadge,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'PAYLOAD_TOO_LARGE', 'UNSUPPORTED_MEDIA_TYPE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 400,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-37',
    service: 'high',
    method: 'delete',
    path: '/system/badges/{id}/image',
    summary: 'حذف تصویر نشان',
    tags: [T.gam],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.badges.manage',
    params: uid,
    response: S.AdminBadge,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-41',
    service: 'high',
    method: 'post',
    path: '/system/announcements',
    summary: 'ارسال پیام همگانی درون‌برنامه‌ای (اینباکس)',
    description: 'مخاطب: همه/کاربران مشخص/نقش سیستمی/اعضای یک جلسه. تحویل غیرهم‌زمان (outbox ⇒ low؛ دسته‌ای). فقط اینباکس (بدون پیامک/پوش — قفل). audit `announcement.send`.',
    tags: [T.msg],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.inbox.send',
    body: S.CreateAnnouncementBody,
    response: S.Announcement,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [{ limit: 10, windowSec: 3600, key: 'user' }],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 300,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-42',
    service: 'high',
    method: 'get',
    path: '/system/announcements',
    summary: 'تاریخچهٔ پیام‌های همگانی',
    tags: [T.msg],
    auth: 'bearer',
    permission: 'system.inbox.send',
    query: pageQuery(50),
    response: S.Announcement,
    list: true,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 150,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-46',
    service: 'high',
    method: 'get',
    path: '/system/announcements/{id}',
    summary: 'جزئیات و آمار تحویل/خواندن یک پیام همگانی',
    tags: [T.msg],
    auth: 'bearer',
    permission: 'system.inbox.send',
    params: uid,
    response: S.Announcement,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-43',
    service: 'high',
    method: 'get',
    path: '/system/users/export',
    summary: 'خروجی CSV کاربران (با فیلترهای H-20)',
    description: 'نیازمند system.users.view هم. حداکثر ۵۰٬۰۰۰ ردیف؛ UTF-8 BOM؛ خنثی‌سازی فرمول. audit `export.users`.',
    tags: [T.exp],
    auth: 'bearer',
    raw: true,
    contentType: 'text/csv; charset=utf-8',
    stepUp: true,
    permission: 'system.data.export',
    query: S.UsersQuery,
    response: z.string(),
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED'],
    rateLimit: [{ limit: 5, windowSec: 600, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 3000,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-44',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/export',
    summary: 'خروجی CSV اعضا/حضور/ارزیابی یک جلسه',
    description: 'نیازمند system.sessions.view هم. audit `export.session`.',
    tags: [T.exp],
    auth: 'bearer',
    raw: true,
    contentType: 'text/csv; charset=utf-8',
    stepUp: true,
    permission: 'system.data.export',
    params: uid,
    query: S.SessionExportQuery,
    response: z.string(),
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 5, windowSec: 600, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 3000,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-45',
    service: 'high',
    method: 'get',
    path: '/system/audit/export',
    summary: 'خروجی CSV گزارش اقدام‌ها (با فیلترهای H-40)',
    description: 'نیازمند system.audit.view هم. حداکثر ۱۰۰٬۰۰۰ ردیف. audit `export.audit`.',
    tags: [T.exp],
    auth: 'bearer',
    raw: true,
    contentType: 'text/csv; charset=utf-8',
    stepUp: true,
    permission: 'system.data.export',
    query: S.AuditQuery,
    response: z.string(),
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED'],
    rateLimit: [{ limit: 5, windowSec: 600, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 3000,
    since: '1.6.0'
  }),
  defineEndpoint({
    id: 'H-48',
    service: 'high',
    method: 'get',
    path: '/system/session-roles',
    summary: 'کاتالوگ مجوزهای قابل‌واگذاری به پشتیبان (فقط‌خواندنی)',
    description: '۱.۷.۰: جایگزین ماتریس نقش‌های جلسه؛ همان خروجی M-68. صاحب جلسه همهٔ این مجوزها را دارد.',
    tags: [T.ses],
    auth: 'bearer',
    response: SessionPermissionCatalog,
    errors: ['AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 3600, etag: true },
    sloP95Ms: 30,
    since: '1.6.0'
  }),
  // ───────── ۱.۷.۰ (docs-v2/31): معیار ارزیابی، پشتیبان، گالری، کامنت ─────────
  defineEndpoint({
    id: 'H-100',
    service: 'high',
    method: 'get',
    path: '/system/evaluation-criteria',
    summary: 'همهٔ معیارهای ارزیابی (فعال و غیرفعال)',
    tags: [T.evc],
    auth: 'bearer',
    permission: 'system.evaluation.manage',
    permissionAny: ['system.sessions.view'],
    response: S.EvaluationCriteriaList,
    errors: ['AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 10, etag: true },
    sloP95Ms: 60,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-101',
    service: 'high',
    method: 'post',
    path: '/system/evaluation-criteria',
    summary: 'ساخت معیار ارزیابی',
    description: 'کلید تکراری ⇒ CONFLICT(KEY_TAKEN)؛ حداکثر ۱۵ معیار ⇒ CONFLICT(LIMIT_REACHED). فقط روی ارزیابی‌های بعدی اثر دارد. رویداد `evaluation.criteria.changed` (⇒ mid). audit `criterion.create`.',
    tags: [T.evc],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.evaluation.manage',
    body: S.CreateCriterionBody,
    response: S.EvaluationCriterion,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 200,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-102',
    service: 'high',
    method: 'patch',
    path: '/system/evaluation-criteria/{id}',
    summary: 'ویرایش معیار ارزیابی (عنوان، وزن، سقف نمره، فعال/غیرفعال، ترتیب)',
    description: 'غیرفعال‌کردن آخرین معیار فعال ⇒ CONFLICT(LAST_ACTIVE_CRITERION). ارزیابی‌های ثبت‌شده snapshot خود را نگه می‌دارند. رویداد `evaluation.criteria.changed`. audit `criterion.update`.',
    tags: [T.evc],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.evaluation.manage',
    params: uid,
    body: S.UpdateCriterionBody,
    response: S.EvaluationCriterion,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-103',
    service: 'high',
    method: 'delete',
    path: '/system/evaluation-criteria/{id}',
    summary: 'حذف معیار ارزیابی (استفاده‌شده ⇒ فقط غیرفعال‌کردن)',
    description: 'معیار استفاده‌شده در ارزیابی ⇒ CONFLICT(CRITERION_IN_USE) (با H-102 غیرفعال کنید)؛ آخرین معیار فعال ⇒ CONFLICT(LAST_ACTIVE_CRITERION). پاسخ = آخرین وضعیت پیش از حذف. رویداد `evaluation.criteria.changed`. audit `criterion.delete`.',
    tags: [T.evc],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.evaluation.manage',
    params: uid,
    response: S.EvaluationCriterion,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-104',
    service: 'high',
    method: 'get',
    path: '/system/users/{id}/supporters',
    summary: 'پشتیبان‌های ثابت یک استاد',
    tags: [T.sup],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    query: SupportersQuery,
    response: TeacherSupporter,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-105',
    service: 'high',
    method: 'put',
    path: '/system/users/{id}/supporters/{supporterId}',
    summary: 'افزودن/تغییر پشتیبان ثابت یک استاد',
    description: 'upsert: نبود ⇒ ساخت، وجود ⇒ جایگزینی مجوزها. پشتیبان باید کاربر فعال باشد (USER_NOT_ACTIVE)؛ خود استاد ⇒ SELF_PROTECTED. audit `supporter.teacher_set`.',
    tags: [T.sup],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: z.object({ id: Id, supporterId: Id }),
    body: SupporterPermissionsBody,
    response: TeacherSupporter,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-106',
    service: 'high',
    method: 'delete',
    path: '/system/users/{id}/supporters/{supporterId}',
    summary: 'حذف پشتیبان ثابت یک استاد',
    description: 'idempotent. audit `supporter.teacher_remove`.',
    tags: [T.sup],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: z.object({ id: Id, supporterId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-107',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/supporters',
    summary: 'پشتیبان‌های مؤثر جلسه (ثابت استاد ∪ per جلسه)',
    tags: [T.sup],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    query: SupportersQuery,
    response: SessionSupporter,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-108',
    service: 'high',
    method: 'put',
    path: '/system/sessions/{id}/supporters/{userId}',
    summary: 'افزودن/تغییر پشتیبان per جلسه',
    description: 'upsert ردیف per جلسه (مجوزهای ثابت استاد دست نمی‌خورند). کاربر فعال لازم (USER_NOT_ACTIVE)؛ صاحب جلسه ⇒ SELF_PROTECTED. audit `supporter.session_set`.',
    tags: [T.sup],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: z.object({ id: Id, userId: Id }),
    body: SupporterPermissionsBody,
    response: SessionSupporter,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-109',
    service: 'high',
    method: 'delete',
    path: '/system/sessions/{id}/supporters/{userId}',
    summary: 'حذف پشتیبان per جلسه',
    description: 'پشتیبان ثابت استاد با H-106 حذف می‌شود. idempotent. audit `supporter.session_remove`.',
    tags: [T.sup],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: z.object({ id: Id, userId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-110',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/galleries',
    summary: 'گالری‌های جلسه (همهٔ سطوح نمایش؛ `occurrenceId?`)',
    tags: [T.gal],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    query: S.AdminGalleriesQuery,
    response: Gallery,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-111',
    service: 'high',
    method: 'post',
    path: '/system/sessions/{id}/galleries',
    summary: 'ساخت گالری برای یک نوبت',
    description: 'حداکثر ۲۰ گالری per نوبت (LIMIT_REACHED). audit `gallery.create`. step-up پیش‌فرض این مجوز none است.',
    tags: [T.gal],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.content.moderate',
    params: uid,
    body: S.AdminCreateGalleryBody,
    response: Gallery,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 300,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-112',
    service: 'high',
    method: 'patch',
    path: '/system/sessions/{id}/galleries/{galleryId}',
    summary: 'ویرایش گالری (عنوان/سطح نمایش/ترتیب)',
    description: 'audit `gallery.update`.',
    tags: [T.gal],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.content.moderate',
    params: z.object({ id: Id, galleryId: Id }),
    body: UpdateGalleryBody,
    response: Gallery,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-113',
    service: 'high',
    method: 'delete',
    path: '/system/sessions/{id}/galleries/{galleryId}',
    summary: 'حذف گالری',
    description: 'حذف نرم؛ فایل‌ها با job پاک می‌شوند. audit `gallery.delete`.',
    tags: [T.gal],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.content.moderate',
    params: z.object({ id: Id, galleryId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-114',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/galleries/{galleryId}/items',
    summary: 'آیتم‌های گالری',
    tags: [T.gal],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: z.object({ id: Id, galleryId: Id }),
    query: GalleryItemsQuery,
    response: GalleryItem,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-115',
    service: 'high',
    method: 'post',
    path: '/system/sessions/{id}/galleries/{galleryId}/items',
    summary: 'بارگذاری فایل در گالری (بدنهٔ خام؛ stream به mid)',
    description:
      'قواعد M-75 (نوع/حجم/magic bytes/EXIF/سهمیه). high بدنه را بدون بافر کامل به MID_ADMIN.galleryItems stream می‌کند (Content-Type و Content-Length همراه). audit `gallery.upload` (بدون محتوا).',
    tags: [T.gal],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.content.moderate',
    params: z.object({ id: Id, galleryId: Id }),
    query: UploadItemQuery,
    rawBody: { contentTypes: [...GALLERY_IMAGE_TYPES, ...GALLERY_AUDIO_TYPES], maxBytes: GALLERY_AUDIO_MAX_BYTES },
    response: GalleryItem,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'PAYLOAD_TOO_LARGE', 'UNSUPPORTED_MEDIA_TYPE', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 3000,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-116',
    service: 'high',
    method: 'delete',
    path: '/system/sessions/{id}/galleries/{galleryId}/items/{itemId}',
    summary: 'حذف آیتم گالری',
    description: 'audit `gallery.item_delete`.',
    tags: [T.gal],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.content.moderate',
    params: z.object({ id: Id, galleryId: Id, itemId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-117',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/galleries/{galleryId}/items/{itemId}/content',
    summary: 'محتوای فایل آیتم گالری (stream از mid؛ Range)',
    description: 'Content-Type = mime آیتم؛ `Range` ⇒ 206 (عبور به mid)؛ `ETag` = sha256؛ `Cache-Control: private, max-age=3600`؛ `X-Content-Type-Options: nosniff`؛ `Content-Disposition: inline`. احراز: Bearer یا URL امضاشده از فیلد `url` آیتم (۱۰ دقیقه، مقید به کاربر)؛ امضای نامعتبر/منقضی ⇒ AUTH_REQUIRED؛ دسترسی کاربرِ امضا هم دوباره بررسی می‌شود.',
    tags: [T.gal],
    auth: 'bearerOrSignedUrl',
    permission: 'system.sessions.view',
    raw: true,
    contentType: 'application/octet-stream',
    rangeRequests: true,
    params: z.object({ id: Id, galleryId: Id, itemId: Id }),
    query: z.object({
      exp: z.coerce.number().int().min(0).optional().meta({ description: 'انقضای امضا (epoch ثانیه)' }),
      u: Id.optional().meta({ description: 'کاربری که URL برایش امضا شده' }),
      sig: z.string().regex(/^[A-Za-z0-9_-]{43}$/).optional().meta({ description: 'HMAC-SHA256 base64url' })
    }),
    response: z.string(),
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 600, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 3600, etag: true },
    sloP95Ms: 250,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-118',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/comments',
    summary: 'کامنت‌های جلسه (`occurrenceId?`، `queueItemId?`، `authorId?`؛ شامل پنهان‌ها)',
    tags: [T.cmt],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    query: S.AdminCommentsQuery,
    response: Comment,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-119',
    service: 'high',
    method: 'patch',
    path: '/system/sessions/{id}/comments/{commentId}',
    summary: 'پنهان/آشکار کردن کامنت',
    description: 'audit `comment.moderate`. step-up پیش‌فرض این مجوز none است.',
    tags: [T.cmt],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.content.moderate',
    params: z.object({ id: Id, commentId: Id }),
    body: ModerateCommentBody,
    response: Comment,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.7.0'
  }),
  defineEndpoint({
    id: 'H-120',
    service: 'high',
    method: 'delete',
    path: '/system/sessions/{id}/comments/{commentId}',
    summary: 'حذف کامنت',
    description: 'حذف نرم؛ idempotent. audit `comment.delete`.',
    tags: [T.cmt],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.content.moderate',
    params: z.object({ id: Id, commentId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.7.0'
  }),
  ...healthEndpoints('high', 'زیرساخت')
] as const;
