import { z } from 'zod';
import { defineEndpoint } from '../core/endpoint';
import { Empty } from '../core/envelope';
import { healthEndpoints } from '../core/ops';
import { Id, pageQuery } from '../core/primitives';
import { SessionInput } from '../domain/session';
import { SetRolesBody, TransitionBody } from '../mid/schemas';
import * as S from './schemas';

const T = { me: 'هویت سیستمی', rbac: 'نقش‌ها، ماژول‌ها و سطح دسترسی', acct: 'حساب من', role: 'نقش‌ها و مجوزها', usr: 'کاربران', ses: 'جلسه‌ها', rep: 'گزارش‌های تحلیلی', set: 'تنظیمات سراسری', aud: 'گزارش‌ها (audit)' };
const rl = { limit: 30, windowSec: 60, key: 'user' } as const;
const uid = z.object({ id: Id });

export const highEndpoints = [
  defineEndpoint({
    id: 'H-00',
    service: 'high',
    method: 'get',
    path: '/system/me',
    summary: 'هویت سیستمی من (نقش‌ها و مجوزها)',
    description: 'کاربر بدون نقش سیستم ⇒ AUTH_FORBIDDEN؛ UI «دسترسی ندارید» نشان می‌دهد.',
    tags: [T.me],
    auth: 'bearer',
    response: S.SystemMe,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 60,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-01',
    service: 'high',
    method: 'get',
    path: '/system/overview',
    summary: 'نمای کلی سیستم',
    tags: [T.me],
    auth: 'bearer',
    response: S.Overview,
    errors: ['AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 10 },
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-10',
    service: 'high',
    method: 'get',
    path: '/system/roles',
    summary: 'فهرست نقش‌ها (سیستمی و پویا) با مجوز، ماژول و قواعد step-up',
    tags: [T.role],
    auth: 'bearer',
    response: S.SystemRole,
    list: true,
    query: pageQuery(10),
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-11',
    service: 'high',
    method: 'get',
    path: '/system/permissions',
    summary: 'فهرست مجوزها (رجیستری پویا؛ هر مجوز در یک ماژول)',
    tags: [T.role],
    auth: 'bearer',
    response: S.PermissionInfo,
    list: true,
    query: pageQuery(50),
    errors: ['AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 300, etag: true },
    sloP95Ms: 40,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-12',
    service: 'high',
    method: 'put',
    path: '/system/roles/{key}/permissions',
    summary: 'ویرایش مجوزهای صریح یک نقش',
    description: 'نقش `developer` ثابت است ⇒ AUTH_FORBIDDEN؛ حذف مجوز قفل‌شده ⇒ CONFLICT(LOCKED_PERMISSION)؛ افزودن مجوزی که خودِ کاربر ندارد ⇒ AUTH_FORBIDDEN (ضد ارتقای دسترسی؛ developer معاف). مجوز ناموجود ⇒ NOT_FOUND. رویداد outbox: `system.permission.changed`.',
    tags: [T.role],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.edit',
    params: z.object({ key: S.SystemRoleKey }),
    body: S.SetRolePermissionsBody,
    response: S.SystemRole,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-20',
    service: 'high',
    method: 'get',
    path: '/system/users',
    summary: 'جست‌وجوی کاربران',
    tags: [T.usr],
    auth: 'bearer',
    permission: 'system.users.view',
    query: pageQuery(50).extend(S.UsersQuery.shape),
    response: S.SystemUser,
    list: true,
    errors: ['AUTH_FORBIDDEN'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 150,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-21',
    service: 'high',
    method: 'get',
    path: '/system/users/{id}',
    summary: 'جزئیات یک کاربر',
    tags: [T.usr],
    auth: 'bearer',
    permission: 'system.users.view',
    params: uid,
    response: S.SystemUserDetail,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-22',
    service: 'high',
    method: 'put',
    path: '/system/users/{id}/roles',
    summary: 'تخصیص/برداشتن نقش سیستم',
    description: 'قفل آخرین دارنده ⇒ CONFLICT(LAST_HOLDER)؛ تغییر نقش developer فقط توسط developer. رویداد outbox: `system.role.changed`.',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.assign',
    params: uid,
    body: S.SetUserRolesBody,
    response: S.SystemUser,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-23',
    service: 'high',
    method: 'put',
    path: '/system/users/{id}/grants',
    summary: 'تعیین مجوزهای مستقیم کاربر (ساخت جلسه)',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.assign',
    params: uid,
    body: S.SetUserGrantsBody,
    response: S.SystemUser,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-30',
    service: 'high',
    method: 'get',
    path: '/system/settings',
    summary: 'تنظیمات سراسری',
    tags: [T.set],
    auth: 'bearer',
    permission: 'system.settings.view',
    response: S.SystemSettings,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 50,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-31',
    service: 'high',
    method: 'put',
    path: '/system/settings',
    summary: 'به‌روزرسانی تنظیمات سراسری (optimistic concurrency)',
    description: '`version` قدیمی ⇒ CONFLICT(VERSION_MISMATCH). وزن جدید فقط روی ارزیابی‌های بعدی اثر دارد (D2). رویداد outbox: `system.settings.changed`.',
    tags: [T.set],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.settings.edit',
    body: S.UpdateSettingsBody,
    response: S.SystemSettings,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.0.0'
  }),
  defineEndpoint({
    id: 'H-40',
    service: 'high',
    method: 'get',
    path: '/system/audit',
    summary: 'گزارش اقدام‌ها (audit؛ فقط‌خواندنی)',
    tags: [T.aud],
    auth: 'bearer',
    permission: 'system.audit.view',
    query: pageQuery(50).extend(S.AuditQuery.shape),
    response: S.AuditEntry,
    list: true,
    errors: ['AUTH_FORBIDDEN'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 200,
    since: '1.0.0'
  }),
  // ───────── حساب من (خودخدمتی؛ بدون permission سیستمی، فقط نقش سیستم) ─────────
  defineEndpoint({
    id: 'H-02',
    service: 'high',
    method: 'get',
    path: '/system/me/account',
    summary: 'حساب من (نام، شماره، وضعیت رمز)',
    tags: [T.acct],
    auth: 'bearer',
    response: S.MyAccount,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 120,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-03',
    service: 'high',
    method: 'patch',
    path: '/system/me/profile',
    summary: 'ویرایش نام و نام‌خانوادگی خودم',
    description: 'ویرایش در low انجام می‌شود (مالک حساب) و رویداد `user.profile.updated` به mid/high می‌رسد. تغییر شمارهٔ موبایل خودخدمتی نیست؛ مدیر با H-25 انجام می‌دهد.',
    tags: [T.acct],
    auth: 'bearer',
    body: S.UpdateMyProfileBody,
    response: S.MyAccount,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-04',
    service: 'high',
    method: 'put',
    path: '/system/me/password',
    summary: 'تعیین/تغییر رمز عبور خودم',
    description: 'نیازمند step-up؛ استثنا: وقتی `MyAccount.mustChangePassword` است `currentPassword` (رمز موقت) به‌جای step-up پذیرفته می‌شود. این تنها مسیر high است که با پرچم رمز موقت (claim `mcp`) مجاز است. پس از موفقیت سایر نشست‌ها revoke می‌شوند.',
    tags: [T.acct],
    auth: 'bearer',
    stepUp: true,
    body: S.SetMyPasswordBody,
    response: Empty,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'AUTH_INVALID_CREDENTIALS'],
    rateLimit: [{ limit: 5, windowSec: 900, key: 'user' }],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-05',
    service: 'high',
    method: 'get',
    path: '/system/me/sessions',
    summary: 'نشست‌ها و دستگاه‌های من',
    tags: [T.acct],
    auth: 'bearer',
    query: pageQuery(50),
    response: S.UserDeviceSession,
    list: true,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 150,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-06',
    service: 'high',
    method: 'delete',
    path: '/system/me/sessions/{id}',
    summary: 'revoke یک نشست خودم',
    tags: [T.acct],
    auth: 'bearer',
    params: uid,
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-07',
    service: 'high',
    method: 'post',
    path: '/system/me/sessions/revoke-others',
    summary: 'خروج از همهٔ نشست‌های دیگرِ خودم',
    tags: [T.acct],
    auth: 'bearer',
    response: Empty,
    errors: ['AUTH_FORBIDDEN'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.4.0'
  }),

  // ───────── مدیریت کاربر (دادهٔ حساب در low؛ high واسطهٔ مجاز + audit) ─────────
  defineEndpoint({
    id: 'H-24',
    service: 'high',
    method: 'post',
    path: '/system/users',
    summary: 'ساخت کاربر',
    description: 'حساب در low ساخته می‌شود و رویداد `user.registered` به high/mid می‌رسد. با `password` رمز موقت است و کاربر در اولین ورود باید عوضش کند. شمارهٔ تکراری ⇒ CONFLICT(PHONE_TAKEN).',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    body: S.CreateUserBody,
    response: S.SystemUserDetail,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-25',
    service: 'high',
    method: 'patch',
    path: '/system/users/{id}',
    summary: 'ویرایش نام/شمارهٔ کاربر',
    description: 'شمارهٔ تکراری ⇒ CONFLICT(PHONE_TAKEN). کاربر حذف‌شده قابل‌ویرایش نیست (CONFLICT USER_NOT_ACTIVE).',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    params: uid,
    body: S.UpdateUserBody,
    response: S.SystemUserDetail,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-26',
    service: 'high',
    method: 'post',
    path: '/system/users/{id}/status',
    summary: 'فعال/غیرفعال‌کردن کاربر',
    description: 'غیرفعال ⇒ همهٔ نشست‌ها revoke و ورود مسدود (AUTH_ACCOUNT_DISABLED). غیرفعال‌کردن خود یا آخرین developer ⇒ CONFLICT(SELF_PROTECTED/LAST_HOLDER).',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    params: uid,
    body: S.SetUserStatusBody,
    response: S.SystemUserDetail,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-27',
    service: 'high',
    method: 'delete',
    path: '/system/users/{id}',
    summary: 'حذف کاربر (حذف نرم + ناشناس‌سازی)',
    description: 'نام/شماره/رمز پاک و نشست‌ها revoke می‌شوند؛ تاریخچهٔ جلسه/حضور/امتیاز با نام «کاربر حذف‌شده» می‌ماند. برگشت‌پذیر نیست. حذف خود یا آخرین developer ⇒ CONFLICT.',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    params: uid,
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-28',
    service: 'high',
    method: 'put',
    path: '/system/users/{id}/password',
    summary: 'تعیین رمز موقت / حذف رمز کاربر',
    description: '`set`: رمز موقت (کاربر در اولین ورود باید عوض کند و نشست‌های او revoke می‌شود). `clear`: حذف رمز؛ ورود فقط با OTP. رمز هرگز لاگ/audit نمی‌شود.',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    params: uid,
    body: S.UserPasswordBody,
    response: Empty,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-29',
    service: 'high',
    method: 'post',
    path: '/system/users/{id}/logout-all',
    summary: 'خروج اجباری کاربر از همهٔ نشست‌ها',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    params: uid,
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-50',
    service: 'high',
    method: 'get',
    path: '/system/users/{id}/sessions',
    summary: 'نشست‌ها و دستگاه‌های یک کاربر (به تفکیک پنل/کلاینت)',
    tags: [T.usr],
    auth: 'bearer',
    permission: 'system.users.view',
    params: uid,
    query: pageQuery(50),
    response: S.UserDeviceSession,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 200,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-51',
    service: 'high',
    method: 'delete',
    path: '/system/users/{id}/sessions/{sessionId}',
    summary: 'revoke یک نشست کاربر',
    tags: [T.usr],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.users.manage',
    params: z.object({ id: Id, sessionId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),

  // ───────── مدیریت جلسه‌ها (دادهٔ جلسه در mid) ─────────
  defineEndpoint({
    id: 'H-60',
    service: 'high',
    method: 'get',
    path: '/system/sessions',
    summary: 'فهرست همهٔ جلسه‌ها با فیلتر',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    query: pageQuery(50).extend(S.AdminSessionsQuery.shape),
    response: S.AdminSession,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 60, windowSec: 60, key: 'user' }],
    cache: 'no-store',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-61',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}',
    summary: 'جزئیات یک جلسه (شامل draft و حذف‌شده)',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    response: S.AdminSession,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 200,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-62',
    service: 'high',
    method: 'post',
    path: '/system/sessions',
    summary: 'ساخت جلسه از طرف یک کاربر',
    description: 'سازنده (پیش‌فرض خود ادمین) session_manager می‌شود؛ جلسه draft است.',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    body: S.AdminCreateSessionBody,
    response: S.AdminSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-63',
    service: 'high',
    method: 'patch',
    path: '/system/sessions/{id}',
    summary: 'ویرایش جلسه (فقط draft/scheduled؛ مثل M-04 ولی بدون نیاز به عضویت)',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: uid,
    body: SessionInput,
    response: S.AdminSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-64',
    service: 'high',
    method: 'post',
    path: '/system/sessions/{id}/transition',
    summary: 'چرخهٔ حیات جلسه: یک قدم رو به جلو',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: uid,
    body: TransitionBody,
    response: S.AdminSession,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SESSION_INVALID_TRANSITION', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-65',
    service: 'high',
    method: 'delete',
    path: '/system/sessions/{id}',
    summary: 'حذف جلسه (حذف نرم؛ از همهٔ فهرست‌های کاربران پنهان می‌شود)',
    description: 'تاریخچهٔ حضور/ارزیابی/امتیاز حفظ می‌شود و فقط در پنل مدیریت (`includeDeleted=true`) دیده می‌شود.',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: uid,
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-66',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/members',
    summary: 'اعضا و درخواست‌های عضویت جلسه',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    query: S.AdminMembersQuery,
    response: S.AdminMember,
    list: true,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-67',
    service: 'high',
    method: 'patch',
    path: '/system/sessions/{id}/members/{memberId}',
    summary: 'تأیید/رد عضویت',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: z.object({ id: Id, memberId: Id }),
    body: S.AdminDecideBody,
    response: S.AdminMember,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-68',
    service: 'high',
    method: 'put',
    path: '/system/sessions/{id}/members/{memberId}/roles',
    summary: 'تعیین نقش‌های درون‌جلسهٔ عضو',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: z.object({ id: Id, memberId: Id }),
    body: SetRolesBody,
    response: S.AdminMember,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-69',
    service: 'high',
    method: 'delete',
    path: '/system/sessions/{id}/members/{memberId}',
    summary: 'حذف عضو از جلسه (نقش مدیر قابل‌حذف نیست)',
    tags: [T.ses],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.sessions.manage',
    params: z.object({ id: Id, memberId: Id }),
    response: Empty,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT', 'SERVICE_UNAVAILABLE'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-70',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/attendance',
    summary: 'حاضرین جلسه (فقط‌خواندنی)',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    response: S.AdminAttendanceList,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-71',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/queue',
    summary: 'صف نوبت جلسه (نمای کامل مدیر، فقط‌خواندنی)',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    response: S.AdminQueue,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-72',
    service: 'high',
    method: 'get',
    path: '/system/sessions/{id}/evaluations',
    summary: 'ارزیابی‌های جلسه (فقط‌خواندنی)',
    tags: [T.ses],
    auth: 'bearer',
    permission: 'system.sessions.view',
    params: uid,
    response: S.AdminEvaluations,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND', 'SERVICE_UNAVAILABLE'],
    cache: 'no-store',
    sloP95Ms: 250,
    since: '1.4.0'
  }),

  // ───────── گزارش‌ها ─────────
  defineEndpoint({
    id: 'H-80',
    service: 'high',
    method: 'get',
    path: '/system/reports/overview',
    summary: 'گزارش جامع (کاربران، جلسه‌ها، مشارکت، پیامک، پنل‌ها) در بازه',
    description: 'بخش‌هایی که سرویس مبدأ در دسترس ندارد `null`/خالی می‌شوند (degraded)، نه خطا.',
    tags: [T.rep],
    auth: 'bearer',
    permission: 'system.reports.view',
    query: S.ReportRangeQuery,
    response: S.ReportOverview,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    rateLimit: [{ limit: 30, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 30 },
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-81',
    service: 'high',
    method: 'get',
    path: '/system/reports/registrations',
    summary: 'سری زمانی ثبت‌نام',
    tags: [T.rep],
    auth: 'bearer',
    permission: 'system.reports.view',
    query: S.ReportSeriesQuery,
    response: S.RegistrationsSeries,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    rateLimit: [{ limit: 30, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 30 },
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-82',
    service: 'high',
    method: 'get',
    path: '/system/reports/sessions',
    summary: 'سری زمانی جلسه‌ها (ساخته‌شده، برگزارشده، حضور)',
    tags: [T.rep],
    auth: 'bearer',
    permission: 'system.reports.view',
    query: S.ReportSeriesQuery,
    response: S.SessionsSeries,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 30, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 30 },
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-83',
    service: 'high',
    method: 'get',
    path: '/system/reports/otp',
    summary: 'سری زمانی پیامک OTP (درخواست/تأییدشده)',
    tags: [T.rep],
    auth: 'bearer',
    permission: 'system.reports.view',
    query: S.ReportSeriesQuery,
    response: S.OtpSeries,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 30, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 30 },
    sloP95Ms: 400,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-84',
    service: 'high',
    method: 'get',
    path: '/system/reports/leaderboard',
    summary: 'برترین کاربران بر اساس امتیاز',
    tags: [T.rep],
    auth: 'bearer',
    permission: 'system.reports.view',
    query: S.LeaderboardQuery,
    response: S.LeaderboardResponse,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'SERVICE_UNAVAILABLE'],
    rateLimit: [{ limit: 30, windowSec: 60, key: 'user' }],
    cache: { scope: 'private', maxAgeSec: 30 },
    sloP95Ms: 300,
    since: '1.4.0'
  }),
  defineEndpoint({
    id: 'H-13',
    service: 'high',
    method: 'post',
    path: '/system/roles',
    summary: 'ساخت نقش پویا',
    description: 'کلید یکتا ⇒ CONFLICT(KEY_TAKEN)؛ مجوز/ماژول ناموجود ⇒ NOT_FOUND؛ مجوزی که سازنده ندارد ⇒ AUTH_FORBIDDEN (developer معاف). Idempotency-Key پشتیبانی می‌شود.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.manage',
    body: S.CreateRoleBody,
    response: S.SystemRole,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 250,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-14',
    service: 'high',
    method: 'get',
    path: '/system/roles/{key}',
    summary: 'جزئیات یک نقش',
    tags: [T.rbac],
    auth: 'bearer',
    permission: 'system.users.view',
    params: z.object({ key: S.SystemRoleKey }),
    response: S.SystemRole,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 80,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-15',
    service: 'high',
    method: 'patch',
    path: '/system/roles/{key}',
    summary: 'ویرایش عنوان/توضیح نقش',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.manage',
    params: z.object({ key: S.SystemRoleKey }),
    body: S.UpdateRoleBody,
    response: S.SystemRole,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-16',
    service: 'high',
    method: 'delete',
    path: '/system/roles/{key}',
    summary: 'حذف نقش پویا',
    description: 'نقش سیستمی ⇒ CONFLICT(SYSTEM_PROTECTED)؛ دارای دارنده ⇒ CONFLICT(ROLE_IN_USE) (ابتدا نقش را از کاربران بردارید). پاسخ = آخرین وضعیت نقش پیش از حذف.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.manage',
    params: z.object({ key: S.SystemRoleKey }),
    response: S.SystemRole,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-17',
    service: 'high',
    method: 'put',
    path: '/system/roles/{key}/modules',
    summary: 'تعیین ماژول‌های کامل نقش',
    description: 'نقش به همهٔ مجوزهای حال و آیندهٔ هر ماژول دسترسی می‌یابد. developer ثابت است. ضد ارتقا: مجوز ماژول که کاربر ندارد ⇒ AUTH_FORBIDDEN. claim دارندگان نقش تازه می‌شود.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.role.manage',
    params: z.object({ key: S.SystemRoleKey }),
    body: S.SetRoleModulesBody,
    response: S.SystemRole,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-18',
    service: 'high',
    method: 'put',
    path: '/system/roles/{key}/step-up',
    summary: 'قواعد step-up هر نقش per مجوز',
    description: 'override نقش روی پیش‌فرض مجوز. موثر برای کاربر: اگر هر منبع (نقش/grant) «required» بگوید ⇒ لازم؛ developer همیشه معاف.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.stepup.manage',
    params: z.object({ key: S.SystemRoleKey }),
    body: S.SetRoleStepUpBody,
    response: S.SystemRole,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-85',
    service: 'high',
    method: 'post',
    path: '/system/permissions',
    summary: 'ساخت مجوز پویا',
    description: 'کلید یکتا ⇒ CONFLICT(KEY_TAKEN)؛ ماژول ناموجود ⇒ NOT_FOUND. مجوز پویا فقط داده است و در JWT/claim برای سرویس‌های مصرف‌کننده می‌آید؛ endpointهای سیستمی فقط مجوزهای سیستمی را اعمال می‌کنند.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.manage',
    body: S.CreatePermissionBody,
    response: S.PermissionInfo,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-86',
    service: 'high',
    method: 'patch',
    path: '/system/permissions/{key}',
    summary: 'ویرایش مجوز',
    description: 'مجوز سیستمی: فقط عنوان/توضیح/step-up پیش‌فرض/grantable؛ جابه‌جایی ماژول فقط برای مجوز پویا.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.manage',
    params: z.object({ key: S.PermissionKey }),
    body: S.UpdatePermissionBody,
    response: S.PermissionInfo,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-87',
    service: 'high',
    method: 'delete',
    path: '/system/permissions/{key}',
    summary: 'حذف مجوز پویا',
    description: 'مجوز سیستمی ⇒ CONFLICT(SYSTEM_PROTECTED). حذف از همهٔ نقش‌ها، grantها و قواعد step-up؛ claim دارندگان تازه می‌شود.',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.manage',
    params: z.object({ key: S.PermissionKey }),
    response: S.PermissionInfo,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 250,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-88',
    service: 'high',
    method: 'get',
    path: '/system/modules',
    summary: 'فهرست ماژول‌ها',
    tags: [T.rbac],
    auth: 'bearer',
    query: pageQuery(50),
    response: S.ModuleInfo,
    list: true,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 60, etag: true },
    sloP95Ms: 60,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-89',
    service: 'high',
    method: 'post',
    path: '/system/modules',
    summary: 'ساخت ماژول',
    description: 'کلید یکتا ⇒ CONFLICT(KEY_TAKEN).',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.manage',
    body: S.CreateModuleBody,
    response: S.ModuleInfo,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'key',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-90',
    service: 'high',
    method: 'patch',
    path: '/system/modules/{key}',
    summary: 'ویرایش ماژول',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.manage',
    params: z.object({ key: S.ModuleKey }),
    body: S.UpdateModuleBody,
    response: S.ModuleInfo,
    errors: ['VALIDATION_FAILED', 'AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-91',
    service: 'high',
    method: 'delete',
    path: '/system/modules/{key}',
    summary: 'حذف ماژول',
    description: 'ماژول سیستمی ⇒ CONFLICT(SYSTEM_PROTECTED)؛ دارای مجوز ⇒ CONFLICT(MODULE_NOT_EMPTY).',
    tags: [T.rbac],
    auth: 'bearer',
    stepUp: true,
    permission: 'system.permission.manage',
    params: z.object({ key: S.ModuleKey }),
    response: S.ModuleInfo,
    errors: ['AUTH_FORBIDDEN', 'AUTH_STEP_UP_REQUIRED', 'NOT_FOUND', 'CONFLICT'],
    rateLimit: [rl],
    cache: 'no-store',
    idempotency: 'natural',
    sloP95Ms: 200,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-92',
    service: 'high',
    method: 'get',
    path: '/system/rbac/matrix',
    summary: 'ماتریس کامل نقش × مجوز × ماژول (یک درخواست برای UI)',
    description: 'همهٔ ماژول‌ها، مجوزها و نقش‌ها همراه قواعد step-up و `version` ماتریس. با If-None-Match ⇒ 304.',
    tags: [T.rbac],
    auth: 'bearer',
    permission: 'system.users.view',
    response: S.RbacMatrix,
    errors: ['AUTH_FORBIDDEN'],
    cache: { scope: 'private', maxAgeSec: 5, etag: true },
    sloP95Ms: 120,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-93',
    service: 'high',
    method: 'get',
    path: '/system/rbac/effective/{id}',
    summary: 'دسترسی مؤثر یک کاربر (با منبع هر مجوز و وضعیت step-up)',
    tags: [T.rbac],
    auth: 'bearer',
    permission: 'system.users.view',
    params: uid,
    response: S.EffectiveAccess,
    errors: ['AUTH_FORBIDDEN', 'NOT_FOUND'],
    cache: 'no-store',
    sloP95Ms: 100,
    since: '1.5.0'
  }),
  defineEndpoint({
    id: 'H-94',
    service: 'high',
    method: 'get',
    path: '/system/me/access',
    summary: 'دسترسی مؤثر من (مجوز، منبع و نیاز به step-up)',
    tags: [T.rbac],
    auth: 'bearer',
    response: S.EffectiveAccess,
    errors: ['AUTH_FORBIDDEN'],
    cache: 'no-store',
    sloP95Ms: 60,
    since: '1.5.0'
  }),
  ...healthEndpoints('high', 'زیرساخت')
] as const;
